### ISSUE TITLE
Enhance forensic-logging-sidecar service to have retry-logic in its error handling sections.

### ISSUE THREAD

**Issue by NicoDuvenage** [mojaloop/mojaloop#104]
**Goal**:
As a Developer I want DB Connectivity to be re-established or retried within the micro-service if there are any connectivity issues to the DB.

**Tasks**:
- [ ] Add retry/re-connectivity logic to DB connectivity code
- [ ] Test retry/re-connectivity logic to DB connectivity code
- [ ] Add unit test for retry/re-connectivity logic to DB connectivity code

**Acceptance Criteria**:
- [ ] Micro-service will retry/re-established connectivity to DB on DB connectivity failures

**Dependencies**:
N/A

**Comment by elnyry** [comment]
Use mojaloop/project/issues to track issues now
