### ISSUE TITLE
Create script to automate provisioning of local development

### ISSUE THREAD

**Issue by NicoDuvenage** [mojaloop/mojaloop#106]
**Goal**:
As a Developer I want a script to assist me with the automated deployments of the Central Components to my local development environment.

**Tasks**:
- [ ] Create script to auto-deploy local K8s deployment for Central Components
- [ ] Test script to auto-deploy local K8s deployment for Central Components

**Acceptance Criteria**:
- [ ] Helm Charts to auto-magically deploy the individual Central Components to K8
- [ ] Helm Charts to auto-magically deploy the entire Central Components to K8

**Dependencies**:
- [ ] K8s environment configured locally with Minikube

**Comment by elnyry** [comment]
central services can be deployed locally with minikube.. outdated issue
