### ISSUE TITLE
Plug in monitoring dashboards for health reporting with persistent storage

### ISSUE THREAD

**Issue by mdebarros** [mojaloop/mojaloop#109]
**Goal**:
As Ops I would like to see a dashboard displaying the health status of the different deployed components and containers with the data persisted to ensure High-Availability.

**Tasks**:
- [ ] Configure persistent storage for all health reporting data

**Acceptance Criteria**:
- [ ] Storage persisting health reporting data
- [ ] Kill monitoring technology/containers with the K8s deployment. Once they are re-deployed by K8 via self-healing the history health reporting data should be available in all dashboards.

**Dependencies**:
- [ ] K8 environment
- [ ] Deployment Monitoring technology

**Comment by elnyry** [comment]
Issue created under mojaloop/project - https://github.com/mojaloop/project/issues/497
