### ISSUE TITLE
Integrate K8 into Continuous Deployment (CD) through CircleCi for publishing Docker Images

### ISSUE THREAD

**Issue by mdebarros** [mojaloop/mojaloop#110]
**Goal**:
As a Developer I want all code changes to be continuously deployed into the Mojaloop Docker-Hub repo when any release branches are tagged

**Tasks**:
- [ ] Configure CircleCI for each GitHub repo that requires CD to publish Docker Image to Docker Hub - Central Services Auth
- [ ] Configure CircleCI for each GitHub repo that requires CD to publish Docker Image to Docker Hub - Central Services Shared
- [ ] Configure CircleCI for each GitHub repo that requires CD to publish Docker Image to Docker Hub - Central Services Database
- [ ] Configure CircleCI for each GitHub repo that requires CD to publish Docker Image to Docker Hub - Central KMS
- [ ] Configure CircleCI for each GitHub repo that requires CD to publish Docker Image to Docker Hub - Central Ledger
- [ ] Configure CircleCI for each GitHub repo that requires CD to publish Docker Image to Docker Hub - Forensic Sidecar Logging
- [ ] Configure CircleCI for each GitHub repo that requires CD to publish Docker Image to Docker Hub - Central Directory
- [ ] Configure CircleCI for each GitHub repo that requires CD to publish Docker Image to Docker Hub - End User Registry
- [ ] Configure CircleCI for each GitHub repo that requires CD to publish Docker Image to Docker Hub - Central Services Error Handling
- [ ] Configure CircleCI for each GitHub repo that requires CD to publish Docker Image to Docker Hub - Pathfinder Query Client
- [ ] Configure CircleCI for each GitHub repo that requires CD to publish Docker Image to Docker Hub - Pathfinder Provisioning Client
- [ ] Configure CircleCI for each GitHub repo that requires CD to publish Docker Image to Docker Hub - Mock Pathfinder
- [ ] Configure CircleCI for each GitHub repo that requires CD to publish Docker Image to Docker Hub - Central Hub

**Acceptance Criteria**:
- [ ] When merges into release branch occurs, CircleCI will build, package and deploy Docker images to Docker Hub Mojaloop org with the approrprate Tag

**Dependencies**:
- [ ] CircleCI Org for Mojaloop
- [ ] GitHub hook configuration into CircleCI to kick-off CD Processes

**Comment by elnyry** [comment]
Outdated; current issues tracked here - https://github.com/mojaloop/project/issues
