### ISSUE TITLE
Integrate K8 into Continuous Deployment (CD) through CircleCi for deploying to K8 cluster

### ISSUE THREAD

**Issue by mdebarros** [mojaloop/mojaloop#111]
**Goal**:
As a Developer I want all code changes to be continuously deployed into the appriate K8 cluster/environment based on the release branch and tags

**Tasks**:
- [ ] Configure CircleCI for each GitHub repo that requires CD to deploy the appropriate Docker Image from Docker Hub to K8s Cluster - Central Services Auth
- [ ] Configure CircleCI for each GitHub repo that requires CD to deploy the appropriate Docker Image from Docker Hub to K8s Cluster - Central Services Shared
- [ ] Configure CircleCI for each GitHub repo that requires CD to deploy the appropriate Docker Image from Docker Hub to K8s Cluster - Central Services Database
- [ ] Configure CircleCI for each GitHub repo that requires CD to deploy the appropriate Docker Image from Docker Hub to K8s Cluster - Central KMS
- [ ] Configure CircleCI for each GitHub repo that requires CD to deploy the appropriate Docker Image from Docker Hub to K8s Cluster - Central Ledger
- [ ] Configure CircleCI for each GitHub repo that requires CD to deploy the appropriate Docker Image from Docker Hub to K8s Cluster - Forensic Sidecar Logging
- [ ] Configure CircleCI for each GitHub repo that requires CD to deploy the appropriate Docker Image from Docker Hub to K8s Cluster - Central Directory
- [ ] Configure CircleCI for each GitHub repo that requires CD to deploy the appropriate Docker Image from Docker Hub to K8s Cluster - End User Registry
- [ ] Configure CircleCI for each GitHub repo that requires CD to deploy the appropriate Docker Image from Docker Hub to K8s Cluster - Central Services Error Handling
- [ ] Configure CircleCI for each GitHub repo that requires CD to deploy the appropriate Docker Image from Docker Hub to K8s Cluster - Pathfinder Query Client
- [ ] Configure CircleCI for each GitHub repo that requires CD to deploy the appropriate Docker Image from Docker Hub to K8s Cluster - Pathfinder Provisioning Client
- [ ] Configure CircleCI for each GitHub repo that requires CD to deploy the appropriate Docker Image from Docker Hub to K8s Cluster - Mock Pathfinder
- [ ] Configure CircleCI for each GitHub repo that requires CD to deploy the appropriate Docker Image from Docker Hub to K8s Cluster - Central Hub

**Acceptance Criteria**:
- [ ] When merges into release branch occurs with an appropriate tag, CircleCI will build, package and deploy Docker images to Docker Hub Mojaloop org with the approrprate Tag.
- [ ] CircleCI as part of the CD process will then instruct K8 cluster to replace the existing deployment image with this newly packaged Docker image for the respective target environment based on the release branch.

**Dependencies**:
- [ ] CircleCI Org for Mojaloop
- [ ] GitHub hook configuration into CircleCI to kick-off CD Processes

**Comment by elnyry** [comment]
Outdated; current issues tracked here - https://github.com/mojaloop/project/issues
