### ISSUE TITLE
Helm improvements

### ISSUE THREAD

**Issue by mdebarros** [mojaloop/mojaloop#115]
**Goal**:
As a Helm user I want a Helm Repository to allow for easy installations, and as a Mojaloop developer I want to be able to configure Helm installation to allow for a local Endpoint for easier development.

**Tasks**:
- [x] Publish Helm Repo via Github pages
- [x] Add External Endpoint feature to each of the Helm Charts
- [x] Update Local Dev Guide for the External Endpoint capability

**Acceptance Criteria**:
- [ ] Helm Repo via Github pages published
- [ ] External Endpoint feature to each of the Helm Charts
- [ ] Updated Local Dev Guide for the External Endpoint capability

**Dependencies**:
- n/a

**Comment by mdebarros** [comment]
PR waiting https://github.com/mojaloop/helm/pull/7

**Comment by elnyry** [comment]
Use mojaloop/project/issues to track issues now
