### ISSUE TITLE
Enhance "common streaming library" for negative use-cases & Integration tests

### ISSUE THREAD

**Issue by mdebarros** [mojaloop/mojaloop#129]
**Goal**:
As a developer I would like to Implement negative use-cases & Integration tests on the "common streaming library"

**Tasks**:
- [ ] Add negative use-cases to Unit tests
- [ ] Add Integration tests

**Acceptance Criteria**:
- [ ] Negative use-cases for Unit Tests in the "common streaming library"
- [ ] Integration tests in the "common streaming library"

**Dependencies**:
- [ ] #148
