### ISSUE TITLE
Update Protocol module of "Common Streaming Library" to validate Protocol messages

### ISSUE THREAD

**Issue by mdebarros** [mojaloop/mojaloop#130]
**Goal**:
Update Protocol module of "Common Streaming Library" to validate Protocol messages

**Tasks**:
- [ ] 

**Acceptance Criteria**:
- [ ] parseMessage to validate Protocol Messages
- [ ] parseCommand to validate Protocol Commands
- [ ] parseNotification to validate Protocol Notification
- [ ] Unit tests are updated to cater for validations

**Dependencies**:
- [ ] #148
