### ISSUE TITLE
Create Integration Tests for Common Streaming Library

### ISSUE THREAD

**Issue by mdebarros** [mojaloop/mojaloop#131]
**Goal**:
As a developer using the Common Streaming Library, I want Integration tests to insure that the Integration aspect of the Streaming Library are properly tested so that it can be included in the CI/CD pipeline

**Tasks**:
- [x] Create Common Streaming Library
- [x] Updated CircleCI v2.0 config to include Integration Tests

**Acceptance Criteria**:
- [x] Integration tests for the Common Streaming Library
- [x] CI/CD executed the Integration Tests as part of the pipelione

**Dependencies**:
- n/a
