### ISSUE TITLE
Integrate K8 into Continuous Integration (CI) through CircleCi

### ISSUE THREAD

**Issue by NicoDuvenage** [mojaloop/mojaloop#21]
**Goal**:
As a Developer I want all code changes to be continuously integrated into the Mojaloop github code-base ensuring that QA checks are done as required before allowing any merges,

**Tasks**:
- [ ] Configure CircleCI for each GitHub repo that requires CI, and Upgrade CircleCI yaml from v1.0 to v2.0 - Central Services Auth
- [ ] Configure CircleCI for each GitHub repo that requires CI, and Upgrade CircleCI yaml from v1.0 to v2.0 - Central Services Shared
- [ ] Configure CircleCI for each GitHub repo that requires CI, and Upgrade CircleCI yaml from v1.0 to v2.0 - Central Services Database
- [ ] Configure CircleCI for each GitHub repo that requires CI, and Upgrade CircleCI yaml from v1.0 to v2.0 - Central KMS
- [ ] Configure CircleCI for each GitHub repo that requires CI, and Upgrade CircleCI yaml from v1.0 to v2.0 - Central Ledger
- [ ] Configure CircleCI for each GitHub repo that requires CI, and Upgrade CircleCI yaml from v1.0 to v2.0 - Forensic Sidecar Logging
- [ ] Configure CircleCI for each GitHub repo that requires CI, and Upgrade CircleCI yaml from v1.0 to v2.0 - Central Directory
- [ ] Configure CircleCI for each GitHub repo that requires CI, and Upgrade CircleCI yaml from v1.0 to v2.0 - End User Registry
- [ ] Configure CircleCI for each GitHub repo that requires CI, and Upgrade CircleCI yaml from v1.0 to v2.0 - Central Services Error Handling
- [ ] Configure CircleCI for each GitHub repo that requires CI, and Upgrade CircleCI yaml from v1.0 to v2.0 - Pathfinder Query Client
- [ ] Configure CircleCI for each GitHub repo that requires CI, and Upgrade CircleCI yaml from v1.0 to v2.0 - Pathfinder Provisioning Client
- [ ] Configure CircleCI for each GitHub repo that requires CI, and Upgrade CircleCI yaml from v1.0 to v2.0 - Mock Pathfinder
- [ ] Configure CircleCI for each GitHub repo that requires CI, and Upgrade CircleCI yaml from v1.0 to v2.0 - Central Hub

**Acceptance Criteria**:
- [ ] CircleCI yaml for each CI enabled GitHub repo upgraded from v1.0 to v2.0
- [ ] CircleCI builds, and tests each GitHub repo that requires CI whenever there is a Pull Request created.
- [ ] GitHub Pull Requests cannot be merged unless QA Build/Test process has been validated by CircleCI

**Dependencies**:
- [ ] CircleCI Org for Mojaloop
- [ ] GitHub hook configuration into CircleCI to kick-off CI Processes

**Comment by mdebarros** [comment]
Currently blocked as I am working on https://app.zenhub.com/workspace/o/mojaloop/mojaloop/issues/113

**Comment by elnyry** [comment]
Outdated issue - currently active issues are tracked under mojaloop/project - https://github.com/mojaloop/project/issues/
