### ISSUE TITLE
Plug in monitoring dashboards for health reporting

### ISSUE THREAD

**Issue by NicoDuvenage** [mojaloop/mojaloop#22]
**Goal**:
As Ops I would like to see a dashboard displaying the health stratus of the different deployed components and containers.

**Tasks**:
- [ ] Choose monitoring technology for K8s cluster
- [ ] Implement monitoring technology for K8s cluster
- [ ] Configure dashboards for Nodes
- [ ] Configure dashboards for Pods
- [ ] Configure dashboards for overal system health

**Acceptance Criteria**:
- [ ] Display a dashboard or resources (cpu, io, memory) of containers
- [ ] Display a dashboard or resources (cpu, io, memory) of nodes
- [ ] Display a dashboard of overall system health

**Dependencies**:
- [ ] K8 environment

**Comment by elnyry** [comment]
Issue created under mojaloop/project - https://github.com/mojaloop/project/issues/498
