### ISSUE TITLE
ALS Implementation to support full CRUD for Admin APIs

### ISSUE THREAD

**Issue by rmothilal** [mojaloop/mojaloop#229]
## **Goal**:
As an implementer of the Switch
I want to support basic, critical functionality on the account-lookup-service
so that basic functionality is available to start with and it can be incrementally improved.
[_Cater for optional currency and type fields for GET /admin/oracles/endpoints _]

**Tasks**:
### Admin API Tasks:
- [ ] Implementation for Admin API for
  - [ ] POST Oracle - 20%
  - [ ] PUT Oracle - 20%
  - [ ] GET Oracle - 20%
  - [ ] DELETE Oracle - 20%
- [ ] Unit tests for Admin API POST Oracle
  - [ ] POST Oracle - 0%
  - [ ] PUT Oracle - 0%
  - [ ] GET Oracle - 0%
  - [ ] DELETE Oracle - 0%

**Acceptance Criteria**:
 - [ ] GET /admin/oracles/endpoints?type={type}&currency={currency}
 - [ ] GET /admin/oracles/endpoints/{ID} - may be required
 - [ ] PUT /admin/oracles/endpoints/{ID}
 - [ ] POST /admin/oracles/endpoints
 - [ ] DELETE /admin/oracles/endpoints/{ID}
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.

**Pull Requests**:
- [ ] TBD

**Follow-up**:
- N/A

**Dependencies**:
- N/A

**Accountability**:
- Owner: @rmothilal @mdebarros 
- QA/Review: @mdebarros @elnyry

**Comment by rmothilal** [comment]
This was created in the incorrect project, it has been recreated in the mojaloop/projects board #705
