### ISSUE TITLE
E2E Transaction

### ISSUE THREAD

**Issue by JoSowden** [mojaloop/mojaloop#267]
## **Goal**:
As a  Contributor to the ML OSS
I want to be able to perform an E2E transaction
so that I can build on this to add PISP functionality

**Tasks**:
- [x] Deploy simulators  to represent the two DFSP's involved in a transaction  ( DFSPA and DFSPB) 
- [x]  Perform a  P2P Transaction from  DFSPA to DFSPB ( Both the quote & transfer steps)
- [x]   Create E2E test for when  DFSPB accepts the transfer request
- [x]   Create E2E test for when  DFSPB rejects the transfer request

**Acceptance Criteria**:
- [x]  Should be able to deploy one or more docker containers, automatically run the integration tests successfully without further intervention
- [x]  A transaction can successfully be performed between the two DFSP's  ( Both the quote and transfer steps)
- [x] an automated E2E test  passes for when DFSPB accepts the transfer request
- [x] an automated E2E test  passes for when DFSPB rejects the transfer request
- [x] Unit Tests pass
- [x] Code Style & Coverage meets standards

## **Pull Requests**:
- [x] https://github.com/mojaloop/pisp/pull/4

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by lewisdaly** [comment]
@lewisdaly to work on docker-compose config and E2E tests for running locally.
@jgeewax spinning up GKS cluster for getting the current tests running.

**Comment by kleyow** [comment]
- Docker-compose setup a bit more troublesome that first anticipated.
- Kubernetes cluster in the progress of being set up in paralell to local docker work.
- Note that there are two simulators to represent dfsps. `simulator` and `mojaloop-simulator`

**Comment by elnyry** [comment]
@kleyow - simulator is being deprecated (its legacy now). 'mojaloop-simulator' is the way to go!

**Comment by lewisdaly** [comment]
> @kleyow - simulator is being deprecated (its legacy now). 'mojaloop-simulator' is the way to go!

Yeah we spoke about this today. We're going to get things up and running with the legacy simulator for now (since it's already well tested, and proven to be working with the current postman collections), and work on replacing it once we are making progress.

**Comment by kleyow** [comment]
GKE deployment mostly stopped by
> error while evaluating the ingress spec: service * is type "ClusterIP", expected "NodePort" or "LoadBalancer"
To fix I need to make GKE use nginx-ingress that ML depends on instead of it using gce/kub's built in ingress.
Still working through that.

Is there a reason why Azure/AWS are the default cloud services for deploying ML?

https://github.com/vessels-tech/moja-box
Talking to Lewis about his old GCE deployment repo.

Been documenting setup commands. Would be really nice to have specific cloud service deployment guides :D

**Comment by lewisdaly** [comment]
>Is there a reason why Azure/AWS are the default cloud services for deploying ML?

They aren't the default, but just what has been used by others for the most part. I never found deploying on GKS too wildly different from deploying locally to Docker for Mac's kubernetes or K3s, but there could be some funny stuff going on with helm and kubernetes versions

>Been documenting setup commands. Would be really nice to have specific cloud service deployment guides :D

Careful what you wish for ;) you might end up writing it yourself

**Comment by kleyow** [comment]
> Careful what you wish for ;) you might end up writing it yourself

Yes. This is exactly what I was leading towards.

re: GCE 

I messaged you, we can talk about it throughout the day.

**Comment by kleyow** [comment]
https://github.com/modusintegration/mbox-mojaloop-helm/tree/master/mojaloop-helm

**Comment by lewisdaly** [comment]
@kleyow this is a ModusBox private repository btw, so we won't be able to see it.

**Comment by kleyow** [comment]
Ah. Yes I put it here since it is supposed to be helpful for the gce
deployment, but let me just slore it elsewhere.
