### ISSUE TITLE
Transaction initiated by PISP 

### ISSUE THREAD

**Issue by JoSowden** [mojaloop/mojaloop#268]
## **Goal**:
As a Payer I want to  initiate a transfer request through a PISP  so that  I don't need to use my DFSP directly

**Tasks**:
- [x] Simulator deployed to represent the PISP
- [x]  PISP sends get/parties request rather than  DFSPA
- [x] Transaction request initiated by PISP using the transactionRequests resource ( see link)
- [x] E2E tests updated to start at the PISP
- [x] investigate if  the simulator can work as a PISP

gitbook sourcecode: 
https://github.com/mojaloop/mojaloop-specification/blob/master/documents/API%20Definition%20v1.0.md#64-api-resource-transactionrequests

gitbook itself
https://mojaloop.io/mojaloop-specification/documents/API%20Definition%20v1.0.html#66-api-resource-authorizations

transaction-requests-service:
https://github.com/mojaloop/transaction-requests-service/blob/master/src/handlers/transactionRequests.js

**Acceptance Criteria**:
- [x] Transaction request initiated by PISP using the transactionrequests resource ( see link)
- [x] PISP handles the acceptance from  DFSPA 
- [x] PISP handles a generic rejection from  DFSPA 
- [x] E2E tests for the the transfer when the DFSPB accepts the transfer pass
- [x] E2E tests for the the transfer when the DFSPB rejects the transfer pass
- [x] Unit Tests pass
- [x] Integration Tests pass
- [x] Code Style & Coverage meets standards

## **Pull Requests**:
- [x] https://github.com/mojaloop/pisp/pull/7

## **Follow-up**:
- N/A

**Dependencies**:
- Need to have decide how will represent in transaction type that is a PISP transfer [#271]

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by eoln** [comment]
To deploy PISP simulator we need to customize the [existing mojaloop](simulator(https://github.com/mojaloop/simulator) so @sridharvoruganti will investigate source code and find out the way to customize it

To deploy PISP simulator we need customized [transactionsRequest service](https://github.com/mojaloop/transaction-requests-service) so @eoln  will investigate source code and find the way to customize it

**Comment by sridharvoruganti** [comment]
OK I am working on simulator customisation as per PISP requirement

**Comment by eoln** [comment]
the available documentation is outdated https://docs.google.com/document/d/17rLpCPM2NY-i4oKGxhlBMbQahGY0k83rij2EOiU_OR4/edit#heading=h.x8l2d7non0ob. There is a call for action to @MichaelJBRichards, @lewisdaly for an explanation of how `/transactionRequests` api should be customized (`FSPIOP-Originator` header or `initiatorId` property in the request body)

**Comment by sridharvoruganti** [comment]
All core service APIs updated to V10.x.x to support transaction request service API. 
With simulator(old) able to initiate transaction request, and it successfully forwarded transaction request from payerfsp to payeefsp. But payerfsp unable to send Quote details as we don't have full implementation for FSP.
Now will investigate whether mojaloop-simulator  can be used for that functionality.

**Comment by eoln** [comment]
simulator investigation: 
- using `rules.json` we can simulate any api endpoint with predefined response
- using `scenarios/`we can simulate any sequence of post/putTransfer operations, to add a new scenario operation we have to customise simulator
- using custom handlers we can deliver any more complex behaviour simulation

**Comment by sridharvoruganti** [comment]
Now  able to initiate transaction request service from mojaloop-simulator , with following  configuration changes.                

- in SDK ALS_ENDPOINT  key changed to ALS_ENDPOINT_HOST 
- TRANSACTION_REQUESTS_ENDPOINT is not yet implemented so workaround without code change is point it to PEER_ENDPOINT
I will check in these changes to branch Pisp/feature/#268-pisp-initiate-transaction

**Comment by eoln** [comment]
I found a workaround to run mojaloop-simulator directly from its repo - it doesn't work out of the box - (there is a need to comment out certificate configuration in scheme-adapter.env)

@ksatya77 is working to get correct docker-compose configuration

**Comment by eoln** [comment]
There is an incoming change in design that will use `thirdPartyRequests Service` instead of `transactionRequests Service` to initiate the transfer by the third party.

**Comment by sridharvoruganti** [comment]
Configuration changes completed , able to initiate transaction request from pisp.
Raised a PR for code review .
