### ISSUE TITLE
Update POST /authorizations

### ISSUE THREAD

**Issue by JoSowden** [mojaloop/mojaloop#269]
## **Goal**:
As a  PISP  I need to be able to show my customer sufficient information so that they can make an informed decision whether to proceed with the transaction

This includes the following calls:
```
| ID      | VERB              | URI                                 | `Source` | `Destination`  |
| ------- | ----------------- | ----------------------------------- | ---- | --- |
| `AG-15` | `POST`            | `/authorizations`                   | DFSPA  | SWITCH |
| `AG-17` | `POST`            | `/authorizations`*2                 | SWITCH | PISP   |
| `AG-26` | `PUT`             | `/authorizations/{ID}`              | PISP   | SWITCH |
```

**Tasks**:
- [x] Update Swagger definition so that POST /authorizations request  from the Payer DFSP contains transaction details and Quote response object.
- [x] Extend enumeration for authentication types to include FIDO
- [x] Tests added for the new authentication types 

**Acceptance Criteria**:
- [ ] Agreed Solution presented to CCB
- [ ] Transaction flow updated to comply with steps 48-68 of  flow  
- [ ] E2E  test for scenario where customer confirms  to PISP transaction should proceed
- [ ] E2E  test for scenario where customer tells PISP transaction should  NOT proceed
- [x] Updated Swagger definition
- [x] Unit Tests pass
- [x] Integration Tests pass
- [x] Code Style & Coverage meets standards
- [x] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [x] TBD

## **Pull Requests**:
- [x] https://github.com/mojaloop/pisp/pull/15/

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by sridharvoruganti** [comment]
sample post /authorizations request :

{             
            "authenticationType": "U2F",
            "retriesLeft": 1,
            "amount": {
              "currency": "USD",
              "amount": "18"
            },
            "transactionId": "2f169631-ef99-4cb1-96dc-91e8fc08f539",
            "transactionRequestId": "02e28448-3c05-4059-b5f7-d518d0a2d8ea",
            "quote": {
              "transferAmount": {
                "currency": "USD",
                "amount": "18"
              },
              "payeeReceiveAmount": {
                "currency": "USD",
                "amount": "0"
              },
              "payeeFspFee": {
                "currency": "USD",
                "amount": "0"
              },
              "payeeFspCommission": {
                "currency": "USD",
                "amount": "0"
              },
              "expiration": "2020-05-17T15:28:54.250Z",
              "geoCode": {
                "latitude": "string",
                "longitude": "string"
              },
              "ilpPacket": "string",
              "condition": "string",
              "extensionList": {
                "extension": [
                  {
                    "key": "string",
                    "value": "string"
                  }
                ]
              }
            }
          }

**Comment by lewisdaly** [comment]
Thanks @sridharvoruganti . Can you please format that nicely using three ticks "```" code blocks?

**Comment by sridharvoruganti** [comment]
Thanks @lewisdaly , I have formatted the sample JSON.
