### ISSUE TITLE
Design how to  determine the originator of a request was a PISP

### ISSUE THREAD

**Issue by JoSowden** [mojaloop/mojaloop#271]
## **Goal**:
As a DFSP  I want to know that the originator of a message I  received is allowed to send messages of that type

**Tasks**:
- [ ] Agree Solution
- [ ] Document Solution
- [ ] Create stories

**Acceptance Criteria**:
- [ ] There is an agreed way of assigning role types to a participant and determining the role type of a participant 
- [ ] The solution is documented
- [ ] Proposed solution approved by DA
- [ ] User stories written to implement the design

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
