### ISSUE TITLE
Update GET /parties to retrieve additional information

### ISSUE THREAD

**Issue by JoSowden** [mojaloop/mojaloop#272]
## **Goal**:
As a `PISP` I want to `be able to retrieve additional information from a DFSP` so that I `have the information required to perform the account linking process`.

Part of account linking process.

Return (as part of Get Parties), return list of accounts
- Array of account objects with a currency and account identifier
- generalize for currencies etc.
- keep Cross-network in mind

> Note: much of this design work has been covered in the Cross Network design. 
> Refer to: [mojaloop-specification#19](https://github.com/mojaloop/mojaloop-specification/issues/19) for more information. 

**Tasks**:
- [x] determine how Access token will be passed through to DFSP to prove that the PISP has AuthN to look at the user's accounts
- [x] modify the GET parties response to include account information (what accounts does the customer hold)
- [x] update the swagger definition(s) according to above design decisions
- [x] Create implementation stories

**Acceptance Criteria**:
- [x] Updates to get/parties agreed and defined in swagger definitions
- [x] The solution is documented 
- [x] User stories written to implement the design
- [x] Outline CCB approval for the design

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by lewisdaly** [comment]
The plan , for x network, is that is _will_ be `GET /parties`, and get additional information back, so it will at least know currencies of the receiver.

We can use the same mechanism in PISP to accomplish this goal. 


Q: Do we need an authorization check between DFSP and PISP? Nope. PISP will be allowed to send a `GET /parties` call.

**Comment by lewisdaly** [comment]
@MichaelJBRichards to take up at the CCB discussion this arvo.
