### ISSUE TITLE
Design solution to inform PISP of transaction outcome

### ISSUE THREAD

**Issue by JoSowden** [mojaloop/mojaloop#273]
## **Goal**:
As a `PISP`
I want to `be informed of the outcome of a transaction`
so that `I can inform my customer`

- Will forward the original `PUT /transfers/{ID}` from the payee DFSP
- The switch will initiate this call (not the DFSP)

Key Questions:
- [x] Can we use the `central-event-processor`? or does this notification make sense elsewhere?
    - this relates to our conversation about whether or not this notification should be in the critical path for a transaction
- [x] How does the switch imply a subscription to a given `PUT /transfers/{ID}` request?

**Tasks**:
- [x] Agree Solution
- [x] Document Solution
- [ ] Create stories

**Acceptance Criteria**:
- [ ] There is an agreed solution as to how a PISP is informed  of the outcome of a transaction
- [ ] The solution is documented
- [ ] The solution is agreed by the DA
- [ ] User stories written to implement the design

## **Pull Requests**:
~- [ ] https://github.com/mojaloop/pisp/pull/16~
- [ ] https://github.com/mojaloop/pisp/pull/55

## **Follow-up**:
- N/A

**Dependencies**:
- #269

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by lewisdaly** [comment]
PISP will get a transfer confirmation response in the same form at the switch and DFSP currently get it.

- This solution is about how we make changes to the switch to 'register' a PISP's interest on the result of a given transfer.
- During the quote request comes through, switch should be able to identify that the originator of request (PISP) will be added to the interested party list.
- If there is a `transferRequestId` associated with the quote, will also add to list of interested parties.

**Comment by lewisdaly** [comment]
See https://github.com/mojaloop/pisp/pull/16 for the current proposal. 

I've done just about as much as I can on this without some other decisions around the nature of the API.

If we are happy with the initial proposal, we may be able to go ahead and start implementing a basic version that uses the existing endpoints (like the other current implementation work), and worry about potentially new services in the future.

**Comment by lewisdaly** [comment]
Latest design thinking has been captured here: https://github.com/mojaloop/pisp/issues/36

**Comment by lewisdaly** [comment]
Rigorous discussion is ongoing here: https://github.com/mojaloop/pisp/issues/42

I would like to have this resolved before the PI, so perhaps we can squeeze in a design discussion by the end of the week.

**Comment by lewisdaly** [comment]
We met yesterday to discuss this. Will be doing some more offline work, but likely will reconvene next week for another design discussion.
