### ISSUE TITLE
Determine new Errors codes that can be received by PISP

### ISSUE THREAD

**Issue by JoSowden** [mojaloop/mojaloop#274]
## **Goal**:
As a PISP
I want to know the error codes I could receive from a DFSP and why i would receive them
so that I can respond to them in the correct way

**Tasks**:
- [x] Determine error scenarios
- [x] Discover kind of new error messages to create
- [x] Ensure they are in Swagger definition
- [x] Assign error codes and messages to the scenarios

**Acceptance Criteria**:
- [x] Initial list of possible error codes and messages documented in Swagger and proposed as API changes
- [x] Document the sort of errors expected for PISP and DFSP and proposed steps 
- [x] Any stories required are created

## **Pull Requests**:
- [x] https://github.com/mojaloop/pisp/pull/11

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
