### ISSUE TITLE
Design a method to determine whether participants are allowed to provide different service

### ISSUE THREAD

**Issue by THEADEV** [mojaloop/mojaloop#277]
## **Goal**:
As a Mojaloop scheme operator I want to be able to define the services that a participant can offer so that I can verify that only approved entities are allowed to provide those services

**Tasks**:
- [x] To define a list of supported roles
- [x] To map each role onto a list of allowed and prohibited API resources 
- [x] Assign roles onto participants

**Acceptance Criteria**:
- [x] Documented list of API resources and roles
- [ ] Specific API calls that will not be accepted
  - [ ] PISP requests a quote
  - [ ] DFSP does a transaction request where it also not the payee.
- [ ]  Latency to be 50ms.
- [ ] Scalability: Peak switch should not be more than 50ms at max rated load for the switch.
        
## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by lewisdaly** [comment]
This is also up for discussion in the DA: https://github.com/mojaloop/design-authority/issues/44

**Comment by lewisdaly** [comment]
First pass at API Calls and Roles is here: https://github.com/vessels-tech/pisp-1/blob/feature/277-role-design/docs/roles.md


This is waiting on feedback from Michael re. the CCB meeting today, but we can also go ahead and update the linking and transaction flow diagrams to ensure we have defined the new and modified API calls correctly.

**Comment by lewisdaly** [comment]
Draft PR here:

https://github.com/mojaloop/pisp/pull/5

I don't feel it's ready to be merged in, since we are still nailing down the final details about the new endpoints.
