### ISSUE TITLE
Set up mojaloop/auth-service repository

### ISSUE THREAD

**Issue by lewisdaly** [mojaloop/mojaloop#278]
## **Goal**:
As a `product owner` I want `the mojaloop/auth-service repo set up` so we can `continue development work, and be ready for the Google interns`

**Tasks**:
- [x] Create a new `mojaloop/auth-service` repo for fido microservice, based on the Mojaloop Typescript template
- [x] refactor wait-for
- [x] properly setup jest and evaluate Cucumber or Gherkin plugins
~- [ ] investigate integration tests and ml-testing-toolkit~ -> Now being covered in #302
- [x] Basic directory structure and getting started readme (most of this can be copied from other projects)
- [ ] Well defined FIDO/Auth Server swagger interfaces  (blocked by #280)
- [x] CI/CD pipelines enabled with basic (failing) tests
- [x] Github Config: Branch protection rules, contributors, owners

**Acceptance Criteria**:
- [ ] PISP repo setup according to above
- [x] Unit Tests fail (hehe... I mean working CI/CD config)
- [x] Working integration test runner for both local and CI/CD

## **Pull Requests**:
- [x] https://github.com/mojaloop/auth-service/pull/1
- [x] https://github.com/mojaloop/auth-service/pull/2
- [x] https://github.com/mojaloop/auth-service/pull/3
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: @lewisdaly 
- QA/Review: @jgeewax

**Comment by lewisdaly** [comment]
Initial repo created here: https://github.com/mojaloop/auth-service

I'm still working on the branch protection rules and default ci/cd config.

**Comment by eoln** [comment]
note related to task CI/CD: too much time spent on reinventing the wheel, so fallback done to derive ci/cd script form central-ledger

**Comment by lewisdaly** [comment]
thanks @eoln, that's probably for the best anyway since keeping our CI/CD scripts close to one another across repos makes managing them much easier.

**Comment by lewisdaly** [comment]
I think this is done now that #280 is closed. @eoln ?

**Comment by eoln** [comment]
yes it is done @lewisdaly I am closing
