### ISSUE TITLE
Set up common tests for mojaloop/pisp repo

### ISSUE THREAD

**Issue by lewisdaly** [mojaloop/mojaloop#279]
## **Goal**:
As a `Product Owner` I want to `have automated testing` so that `we can deliver a high quality and reliable product`

**Tasks**:
- [x] Determine scope of tests. What types of tests, and how do we separate them?
- [x] Determine appropriate tooling (Jest, Cucumber, ml-testing-toolkit, postman, etc)
- [ ] Implement test scaffolding for each type
- [x] Add CI/CD config to run tests automatically

**Acceptance Criteria**:
- [x] Working local test environment, (for everyone, not just 'on my machine')
- [x] Working CI/CD test environment, configured to build master branch, pull requests and releases
- [x] Code Style & Coverage meets standards

## **Pull Requests**:
- [x] https://github.com/mojaloop/pisp/pull/8
- [x] https://github.com/mojaloop/pisp/pull/14

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: @lewisdaly 
- QA/Review: TBC

**Comment by lewisdaly** [comment]
As we discussed yesterday, this will also require the fixing of some of the docker-compose config so it starts on the first run.

**Comment by lewisdaly** [comment]
We have working end to end tests!

https://app.circleci.com/pipelines/github/mojaloop/pisp/8/workflows/e167d559-f908-4a8f-b1f0-9d337d21a523/jobs/15
