### ISSUE TITLE
Design API Spec for AuthN Service (FIDO)

### ISSUE THREAD

**Issue by lewisdaly** [mojaloop/mojaloop#280]
## **Goal**:
As a `participant` I want to `have an interface which will enable me to obtain reliable authn which will be trusted by all other participants in the system` so I can `implement PISP user enrolment and attestation flows`

- store credential, validate credential, generate challenge

**Tasks**:
- [x] Design API Authentication service API 
- [x] Update API swagger specification(s)
~- [ ] Tentative CCB approval~ no longer really relevant as these are separate APIs now
- [x] Identify and prepare high level test scenarios 

**Acceptance Criteria**:
- [x] Updated swagger definitions for FSPIOP API
- [x] Documented design decisions and AuthN flows
- [x] List of test scenarios
- [x] New design stories relating to linking process
- [x] New implementation stories relating to this API Spec (both linking and transfer-attestation steps)

## **Pull Requests**:
- [x] https://github.com/mojaloop/auth-service/pull/7
- [x] https://github.com/mojaloop/auth-service/pull/8
- [ ] https://github.com/mojaloop/pisp/pull/39

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by lewisdaly** [comment]
Notes on the proposal for linking here:
 https://github.com/mojaloop/pisp/issues/19

**Comment by lewisdaly** [comment]
@jgeewax I think we're just waiting for your PR with the updated sequence diagrams, and we can close this.

**Comment by jgeewax** [comment]
@lewisdaly : https://github.com/mojaloop/pisp/pull/39
