### ISSUE TITLE
PCI DSS Gap Analysis - Requirement 1 : Secure Network and Systems

### ISSUE THREAD

**Issue by godfreykutumela** [mojaloop/mojaloop#283]
## **Goal**:
Perform PCI DSS gap analysis as part of the overall compliance baseline initiative within Mojaloop.

**Tasks**:
- [ ] Custom-tune PCI DSS assessment template to Mojaloop setup [ @godfreykutumela ]
- [ ] Perform the assessment for requirement 1 - Secure Network and Systems [ @godfreykutumela ]
- [ ] Compile a report [ @godfreykutumela ]

**Acceptance Criteria**:
- [ ] Completed Gap Analysis Report

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: @godfreykutumela 
- QA/Review: @rasputtintin

**Comment by godfreykutumela** [comment]
Issue moved to [mojaloop/project #1353](https://github.com/mojaloop/project/issues/1353) via [**ZenHub**](https://www.zenhub.com/)
