### ISSUE TITLE
PCI DSS Gap Analysis - Requirement 2 : Defaults for system passwords 

### ISSUE THREAD

**Issue by godfreykutumela** [mojaloop/mojaloop#284]
## **Goal**:
Perform PCI DSS Gap Analysis for Requirement 2 - defaults for system passwords. 

**Tasks**:
- [ ] Create a template [ @godfreykutumela ]
- [ ] Perform the assessment [ @godfreykutumela ]
- [ ] Compile a report [ @godfreykutumela ]

**Acceptance Criteria**:
- [ ] A completed report

## **Accountability**:
- Owner: @godfreykutumela 
- QA/Review: @rasputtintin

**Comment by godfreykutumela** [comment]
Issue moved to [mojaloop/project #1352](https://github.com/mojaloop/project/issues/1352) via [**ZenHub**](https://www.zenhub.com/)
