### ISSUE TITLE
PCI DSS Gap Analysis - Requirement 5 : Vulnerability Management Program

### ISSUE THREAD

**Issue by godfreykutumela** [mojaloop/mojaloop#287]
## **Goal**:
Perfom a PCI DSS Gap Analysis for requirement 5 : Vulnerability Management Program of the PCI DSS Standard

**Tasks**:
- [ ] Create a template [ @godfreykutumela ]
- [ ] Perform an assessment [ @godfreykutumela ]
- [ ] Compile a report [ @godfreykutumela ]

**Acceptance Criteria**:
- [ ] Designs are up-to date

## **Accountability**:
- Owner: @godfreykutumela 
- QA/Review: @godfreykutumela

**Comment by godfreykutumela** [comment]
Issue moved to [mojaloop/project #1349](https://github.com/mojaloop/project/issues/1349) via [**ZenHub**](https://www.zenhub.com/)
