### ISSUE TITLE
PCI DSS Gap Analysis - Requirement 8 : Identify and authenticate access to system components

### ISSUE THREAD

**Issue by godfreykutumela** [mojaloop/mojaloop#290]
## **Goal**:
Perform a PCI DSS Gap Analysis for requirement 8 : Identify and authenticate access to system components.

**Tasks**:
- [ ] Create a template [ @godfreykutumela  ]
- [ ] Perform an assessment [ @godfreykutumela ]
- [ ] Compile report [ @godfreykutumela ]

**Acceptance Criteria**:
- [ ] Completed report

## **Accountability**:
- Owner: @godfreykutumela 
- QA/Review: @godfreykutumela

**Comment by godfreykutumela** [comment]
Issue moved to [mojaloop/project #1345](https://github.com/mojaloop/project/issues/1345) via [**ZenHub**](https://www.zenhub.com/)
