### ISSUE TITLE
[docker-local] - Investigate a clean solution to DNS resolution for PISP's docker setup on Linux based OS's.

### ISSUE THREAD

**Issue by kleyow** [mojaloop/mojaloop#296]
## **Goal**:
As a developer I want to run the PISP local mojaloop without having to battle DNS issues.

**Tasks**:
- [ ] Implement a solution that resolves the service DNS's without using the `extra_hosts` option.

**Acceptance Criteria**:
- [ ] Setup runs and tests pass under solution.
- [ ] Code Style & Coverage meets standards

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by lewisdaly** [comment]
Not a critical issue, nice to have.

**Comment by lewisdaly** [comment]
We should look into this a little more if we want to spin out docker-local into it's own 'thing'.

**Comment by lewisdaly** [comment]
Issue moved to [mojaloop/project #1821](https://github.com/mojaloop/project/issues/1821) via [**ZenHub**](https://www.zenhub.com/)
