### ISSUE TITLE
components binding diagram for docker-local

### ISSUE THREAD

**Issue by eoln** [mojaloop/mojaloop#299]
## **Components binding diagram**:
As a developer, I want to see how components are connected so that the structure of the system is clear for me

**Tasks**:
- [x] document bindings between components
- [x] visualize the bindings on diagram

**Acceptance Criteria**:
- [x] bindings and their relations are well specified in the docker-compose config file/s
- [x] diagram

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
