### ISSUE TITLE
Contract tests between PISP Simulator and ml-testing-toolkit

### ISSUE THREAD

**Issue by lewisdaly** [mojaloop/mojaloop#302]
## **Goal**:
As a `product owner` I want to `have API contract tests configured between the PISP simulator and ml-api-adapter` so I can `have a reliable interface between PISPs and Mojaloop`.

**Tasks**:
- [x] in the `mojaloop/pisp` repo, set up a new `docker-compose` config so that we can run a PISP simulator alongside the `ml-testing-toolkit`
- [x] implement a specific PISP feature or endpoint (for example, receiving a `POST /authorization` from the switch) in the ml-testing-toolkit and pisp simulator
     - As /authorizations flow is not yet implemented in schema-adapter, configured direct URL(http://mojaloop-testing-toolkit:15000/authorizations) to test it. 

- [x] needs to create a pisp simulator image, based on a feature branch of the `mojaloop/mojaloop-simulator`
- [x] Write instructions for running the contract tests manually, with an eye to future automation.

**Acceptance Criteria**:
- [x] `docker-compose` setup with custom pisp simulator and ml-testing-toolkit
- [x] example readme.md with manual contract tests
- [x] implemented one use case (see above) for an api call

## **Pull Requests**:
- [x] https://github.com/mojaloop/pisp/pull/27

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by sridharvoruganti** [comment]
Working on first task, set up a new docker-compose config to run a PISP simulator alongside the ml-testing-toolkit.

**Comment by sridharvoruganti** [comment]
working on readme file
