### ISSUE TITLE
Implement `POST /authorizations`

### ISSUE THREAD

**Issue by lewisdaly** [mojaloop/mojaloop#305]
## **Goal**:
As a `DFSP` I want to `send a POST /authorizations` so that `the PISP can receive the quote included in the Authorizations request`

### Notes
- Updated swagger definitions [pisp/fspiop-rest](https://github.com/mojaloop/pisp/blob/master/docs/fspiop-rest-v1.0-OpenAPI-implementation.yaml#L1647)
- Existing swagger definition for [`transaction-request-service`](https://github.com/mojaloop/transaction-requests-service/blob/master/src/interface/swagger.json) - I think this will need to be updated as well.
- [Existing `Authorizations` handlers](https://github.com/mojaloop/transaction-requests-service/blob/master/src/handlers/authorizations/%7BID%7D.js)

**Tasks**:
- [x] `CI/CD customization` to generate -pisp image for transaction-request-service
- [x] `POST /authorizations` in transaction-request-service & update pisp/master & fix Money
- [x] `POST /authorizations` in the sdk-scheme-adapter (from DFSP -> Switch: OutbondServer):
  - update sequences.puml
  - update swagger definitions on OutboundServer
  - implement & unit-tests OutboundServer
  - update swagger definitions on InboundServer, check is there a need to update existing flows
  - implement, adjust & unit-tests InboundServer
- [x] `POST /authorization` in sdk-standard-components (DFSP -> Switch) (@lewisdaly to take this one up)
  - implement basic copy of mojaloop-requests into thirdparty-requests
  - add new `POST /authorizations`
  - implement unit tests
  - factor out common code between mojaloop-requests and thirdparty-requests
  - add documentation and usage guide for `POST /authorizations`
- [ ] ~~`POST /authorizations` in ml-api-adapter (from Switch -> PISP)~~
- [ ] ~~`POST /authorizations` in central-ledger (from Switch -> PISP)~~
- [x] integration tests in mojaloop/pisp

**Acceptance Criteria**:
- [x] Designs are up-to date
- [x] Unit Tests pass
- [x] Integration Tests pass
- [x] New e2e test for `POST /authorizations`
- [x] Code Style & Coverage meets standards
- [ ] TBD

## **Pull Requests**:
- [x] https://github.com/mojaloop/transaction-requests-service/pull/39
- [x] https://github.com/mojaloop/transaction-requests-service/pull/40
- [x] https://github.com/mojaloop/transaction-requests-service/pull/41
- [x] https://github.com/mojaloop/sdk-scheme-adapter/pull/170

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by eoln** [comment]
@lewisdaly could you please add links to documentation? 
Is this https://docs.google.com/document/d/17rLpCPM2NY-i4oKGxhlBMbQahGY0k83rij2EOiU_OR4/edit#heading=h.eohpx2lwwaw 
still valid?

**Comment by lewisdaly** [comment]
@eoln the google doc is a good reference, but you are correct in that the updated swagger spec is the one to look for. 

I've been thinking a little about the implementation of this, and where this code should live. As @elnyry noted yesterday, `authorizations` is currently a part of the transaction-request-service.

For now, I think we should implement the new `POST` verb here, but this may need to change in the future.

**Comment by eoln** [comment]
@lewisdaly I got confirmation from @rmothilal that implementing forwarding of the POST /authorization in ml-api-adapter and in central-ledger isn't necessary because already message forwarding logic DFSP -> transaction-request-service (SWITCH) -> PISP is already implemented:
So, when DFSP calls POST /authorizations on transaction-request-service the internal code use require('@mojaloop/central-services-shared').Util.Request  with endpoint resolved from require('@mojaloop/central-services-shared').Util.Endpoints.getEndpoint  here: https://github.com/mojaloop/transaction-requests-service/blob/pisp/master/src/domain/authorizations/authorizations.js#L86 .

**Comment by lewisdaly** [comment]
Great! Thanks for the update @eoln
