### ISSUE TITLE
microservice template & generation

### ISSUE THREAD

**Issue by eoln** [mojaloop/mojaloop#308]
## **Generate microservice from template**:
As a Developer,
I want to generate microservice repo from the template (auth-service)
so that I have an easy start with repo layout, dependencies, jest&bdd and full CI/CD pipeline

**Tasks**:
- [ ] select scaffolding app: Yeoman, Hygen, others...
- [ ] repo dedicated to templates
- [ ] identify customisation parameters
- [ ] generator cli

**Acceptance Criteria**:
- [ ] Repo scaffolded
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by lewisdaly** [comment]
I think a much simpler approach would be to update the Typescript Template repo we already have:

https://github.com/mojaloop/template-typescript-public

In that, we have some setup steps, and global find and replace and circleci templates based on the type of repo it is.

**Comment by eoln** [comment]
manual setup from template could be error-prone and time-consuming when yeoman generators could mitigate these types of risk

**Comment by lewisdaly** [comment]
Closing as out-of-scope for now. We may want to reopen at a later date.
