### ISSUE TITLE
TS Types for @mojaloop/<shared_lib>

### ISSUE THREAD

**Issue by eoln** [mojaloop/mojaloop#309]
## **Typescript support for @mojaloop/<shared_lib>**:
As a Developer 
I want to have `index.d.ts` specification for shared libraries
so that I can leverage strict typing when using these libraries

**Tasks**:
- [ ] Select which libraries are required to have `index.d.ts`
- [ ] Implement types for every library

**Acceptance Criteria**:
- [ ] Document way of working when creating `.d.ts`
- [ ] Every library has it's own types
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by lewisdaly** [comment]
I suppose this is a nice to have, rather than a critical thing at the moment... although if we were going to do it, it would make sense to do it now rather than later as we will get a lot more benefit from having the types.

**Comment by eoln** [comment]
Yes, it isn't critical, but using strict Typescript in mixed mode could be a nightmare of multi-type casting. It is not blocking because we can use the `declare module` declaration in ambient.d.ts to add the ad-hoc missed type declarations. I tagged it `nice-to-have` and let keep this story parked.

**Comment by lewisdaly** [comment]
I think we've got established a good mix for now. We have an `index.d.ts` for sdk-standard-components. Next up, I think we should add an `index.d.ts` for `central-services-shared`. 

Closing this ticket. Please reopen with a more specific library if you think we still need this on our roadmap.
