### ISSUE TITLE
OpenAPI reusable snippets

### ISSUE THREAD

**Issue by eoln** [mojaloop/mojaloop#311]
## **Goal: let use reusable OpenAPI snippets to define interface**:
As a **Developer** 
**I want to** library of reusable OpenAPI mojaloop snippets 
**so that** I can specify API interface in a normalized way

**Tasks**:
- [x] investigate splitting possibilities https://azimi.me/2015/07/16/split-swagger-into-smaller-files.html
- [x] resolve OpenAPI references 
- [x] validate resolved OpenAPI interface

**Acceptance Criteria**:
- [x] snippets library (YAML) (mojaloop/api-snippets)
- [x] @hapi server helper to resolve OpenAPI references
- [x] Code Style & Coverage meets standards
- [x] change to common element is reflected in dependent APIs
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by lewisdaly** [comment]
Discussion in meeting today:

- we will want a centrally hosted repository for swagger snippets (mojaloop-specification? or another repo?)
- a published npm module that can be used to recompile the swagger definition for a given repository
  - e.g. `npm run update-swagger-spec`
- in a mojaloop repository (e.g. `ml-api-adapter`), you define a "skeleton" swagger definition that refers to the `refs` in mojaloop-specificaion

`npm run update-swagger-spec` will take the skeleton swagger definition and output a fullly resolved swagger file (`json` or `yaml`)
