### ISSUE TITLE
Set up thirdparty-api-adapter repo

### ISSUE THREAD

**Issue by lewisdaly** [mojaloop/mojaloop#312]
## **Goal**:
As a Hub operator, I want a new service for handling HTTP requests from third parties so they can be appropriately separated from the ml-api-adapter

**Tasks**:
- [x] new repository setup (same as the auth-service)
- [x] Basic directory structure and getting started readme (most of this can be copied from other projects)
- [x] CI/CD pipelines enabled with basic tests
- [x] Github Config: Branch protection rules, contributors, owners

**Acceptance Criteria**:
- [x] `thirdparty-api-adapter` repo setup according to above
- [x] basic unit tests
- [x] Working integration test runner for both local and CI/CD

## **Pull Requests**:
- [x] https://github.com/mojaloop/thirdparty-api-adapter/pull/1

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
