### ISSUE TITLE
thirdparty-api-adapter, handle POST /thirdpartyRequests/transactions

### ISSUE THREAD

**Issue by lewisdaly** [mojaloop/mojaloop#313]
## **Goal**:
As a `hub operator`,
I want to `be able to handle POST /thirdpartyRequest/transaction from a PISP` 
so I `can kick off the 3rd party transaction flow.`

`POST /thirdpartyRequest/transaction` is a passthrough function, the only thing the switch needs to do is find the correct endpoint for the dfsp specified in `FSPIOP-Destination`, and forward the request on.

A rough flow looks like:
1. receive inbound 
2. perform validation, return with appropriate error if invalid, otherwise `202 Accepted`
3. Get the dfsp from the  `FSPIOP-Destination` header
4. Lookup the endpoint from the central-ledger, with type something like: `THIRDPARTY_CALLBACK_URL_REQUESTS_POST`
5. Send the request to this party

Registering the `THIRDPARTY_CALLBACK_URL_REQUESTS_POST` endpoint type will be taken care of in [#355](https://app.zenhub.com/workspaces/pisp-5e8457b05580fb04a7fd4878/issues/mojaloop/mojaloop/335)

Refer to the latest version of the Transfer sequence diagrams for more information about each call: https://github.com/vessels-tech/pisp-1/tree/feature/transfers-api-design/docs#transfer

**Tasks**:
- [x] inbound handler for `POST /thirdpartyRequest/transaction`
- [x] lookup the Endpoint for this callback (central-ledger implementation will be covered in [#355](https://app.zenhub.com/workspaces/pisp-5e8457b05580fb04a7fd4878/issues/mojaloop/mojaloop/335))
- [x] send outbound request to DFSP
- [x] declare required Types
- [x] new unit and integration tests
  - [x] can stub out the central-ledger for unit tests
  - [x] integration tests will need to pre-register the endpoint and fetch from central-ledger
- [x] Replace hapi-openapi with the openapi-backend
- [x] Convert the existing swagger spec to use the mojaloop/api-snippets library 
_e2e and contract tests will be covered elsewhere_

**Acceptance Criteria**:
- [x] `POST /thirdpartyRequests/transactions` implemented as above
- [x] Unit Tests pass
- [x] Integration Tests pass
- [x] Code Style & Coverage meets standards

## **Pull Requests**:
- [x] https://github.com/mojaloop/thirdparty-api-adapter/pull/12
- [x] https://github.com/mojaloop/central-services-shared/pull/242
- [x]  https://github.com/mojaloop/pisp/pull/48

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by lewisdaly** [comment]
@lewisdaly to link and add sequence diagrams before we size this

**Comment by lewisdaly** [comment]
```
POST /thirdpartyRequest/transaction
FSPIOP-Source: switch
FSPIOP-Destination: pispa
{
    "quoteId": "7c23e80c-d078-4077-8263-2c047876fcf6",
    "transactionId": "85feac2f-39b2-491b-817e-4a03203d4f14",
    "transactionRequestId": "8d34f91d-d078-4077-8263-2c047876fcf6",
    "payee": {
        "partyIdInfo": {
            "partyIdType": "MSISDN",
            "partyIdentifier": "+44 1234 5678",
            "fspId": "DFSP B"
        }
    },
    "payer": {
        "accountId": 'dfspa.1234-5678',//this was agreed upon during linking
        "personalInfo": {
            "complexName": {
                "firstName": "Ayesha",
                "lastName": "Takia"
            }
        },
        "partyIdInfo": {
            "partyIdType": "MSISDN",
            "partyIdentifier": "+44 8765 4321",
            "fspId": "DFSP A"
        }
    },
    "amountType": "RECEIVE",
    "amount": {
        "amount": "100",
        "currency": "USD"
    },
    "transactionType": {
        "scenario": "TRANSFER",
        "initiator": "PAYER", 
        "initiatorType": "CONSUMER"
    },
    "expiration": "2020-02-15T22:17:28.985-01:00"
}


}
```
