### ISSUE TITLE
Swagger Interface Definition for thirdparty-api-adapter (PISP only)

### ISSUE THREAD

**Issue by lewisdaly** [mojaloop/mojaloop#316]
## **Goal**:
As a `hub operator` I want to `ensure that entities in a PISP role can only perform a subset of tasks` so that `PISPs can integrate with me`

**Tasks**:
- [x] define the swagger interface for the new `thirdparty-api-adapter`
  - [x] refer to this section: https://github.com/mojaloop/pisp/blob/master/docs/roles_and_endpoints.md#thirdparty-api-pisp---switch for a list of api endpoints
  - [x] @lewisdaly to double check `Request Challenge` once we have a better handle of the Linking flow
  - [x] refer to this draft PR for some consents and consent requests: https://github.com/mojaloop/pisp/pull/20
  - [x] Refer to this doc for `thirdpartyRequests/transfer`:  https://raw.githubusercontent.com/mojaloop/pisp/feature/transfers-api-design/docs/out/transfer/api_calls_detailed/PISPTransferDetailedAPI-page2.png
- [x] add endpoints that are not covered in other stories (existing endpoints from Mojaloop API)
  - `getParties`
  - `update authorization`

**Acceptance Criteria**:
- [x] new swagger specification for `thirdparty-api-adapter`
- [ ] DA approval 

## **Pull Requests**:
- [x] https://github.com/mojaloop/thirdparty-api-adapter/pull/2

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by lewisdaly** [comment]
![Screen Shot 2020-06-04 at 11.46.55 am.png](https://images.zenhubusercontent.com/5cd963af3613073e20e46e60/b3b91ca0-2ddd-4b33-bf3c-799bde6e0c13)

This image describes the api topology we have agreed upon. 

We also have DA approval on the above, as discussed in https://github.com/mojaloop/design-authority/issues/47

**Comment by sridharvoruganti** [comment]
**ThirdParty-PISP-API (PISP -> Switch) endpoints**

1. GET  /parties/{Type}/{ID}*
2. PUT /authorizations/{ID}
3. POST /consentRequests
4. PUT	/consentRequests/{ID}
5. PUT	/consents/{ID}/createCredential
6. GET	/consents/{ID}
7. PUT	/consents/{ID}
8. POST /thirdPartyRequest/transactions
9. GET	/thirdPartyRequest/transactions/{ID}
