### ISSUE TITLE
sdk-scheme-adapter role configuration

### ISSUE THREAD

**Issue by lewisdaly** [mojaloop/mojaloop#318]
## **Goal**:
As a `participant (PISP, DFSP, other)`
I want to `use the scheme adapter and its api subsets in a role specific way`
so that I can `easily connect to the mojaloop switch without worrying about APIs I need not concern myself with`.

We want a single scheme-adapter that supports each api (mojaloop-api, thirdparty-api, possibly even thirdparty-dfsp-api), and can be configured to handle one more more of these APIs at the same time. 

This may not end up being a _lot_ of work, and indeed, it could be something very easily taken care of in `src/config.js` of the scheme adapter. We will likely want to refactor `OutboundServer` into separate parts that can be composed into a cohesive implementation given the role config.

For example, `OutboundServer` could be broken up into 
- `CommonServer`: `GET /parties`
- `Transfers`: quotes, transfers, transactionRequests (all of the current FSPIOP api stuff that isn't common)
- `ThirdpartyServer`: `POST /thirdpartyRequests/...`, `consentRequests`

>Note: these are suggestions only, and part of this ticket is to figure out the strategy, and get the blessings from the maintainers of the sdk-scheme-adapter.

This can be implemented in state machine(s) within the sdk-scheme-adapter, which doesn't explicitly require multiple _roles_ as above.

**Tasks**:
- [ ] determine a backwards-compatible approach for specifying roles in the sdk-scheme-adapter configuration. For now, roles will be DFSP, PISP, but this needs to be extensible
- [ ] determine how we might break down the sdk-scheme-adapter outbound api into a sensible set of functions/classes that be composed into one cohesive API depending on a Role.
- [ ] implement the above breakdown for the existing scheme-adapter (no need to add any new PISP calls just yet, that will be covered elsewhere.

**Acceptance Criteria**:
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by lewisdaly** [comment]
This can likely be handled by state machine models internally to the sdk-scheme-adapter (`thirdpartyRequests/transactions`, `consentRequests`, `consents`)

**Comment by lewisdaly** [comment]
@lewisdaly to update this story according to latest discussion.

**Comment by lewisdaly** [comment]
I'm going to close this one, and open new tickets for each use case/state machine.
