### ISSUE TITLE
Design: Figure out what to do about the `Authorizations` resource

### ISSUE THREAD

**Issue by lewisdaly** [mojaloop/mojaloop#319]
## **Goal**:
As an `OSS design team` 
I want to `determine where to implement changes to the authorizations resource` 
so that `the codebase remains maintainable, efficient and scalable` 

In the current implementation, the `authorizations` resource is handled by the `transaction-requests-service`. That is because the existing scope of authorizations implicitly suggested that a transactionRequest is also needed.

With PISP, this implicit behaviour breaks down, since calls to the `authorizations` resource can be related to a `thirdpartyRequest/transaction`, which lives in a completely separate API. 

For the PISP transaction to work, we need a new verb `POST /authorizations`, in order to return the quote/authorization details to a PISP. So the question is, where should this implementation in the switch live?

Suggested options:
1. Implement in the existing `transaction-requests-service`. This is the easiest place to put it, since the existing implementation is already there. 
2. Add the new `POST /authorizations` call to the new thirdparty-api, and hence handle it in the thirdparty-api-adapter. This kind of makes sense to me (it's a _new_ feature for the thirdparty use case, so that somewhat makes sense to me. This does fragment the API a little more, and make it harder to implement.
3. Refactor all of `authorizations` into a new microservice. This would take a lot of work, and doesn't deliver much immediate value. It could make life easier down the line in case we want to reuse `authorizations` for another 3rd purpose in the future.

**Tasks**:
- [x] discuss the above and make a decision (we chose #1)
- [x] record decision and update necessary documentation
- [x] implementation stories for the `POST /authorizations` and any other relevant stories depending on our decision above

**Acceptance Criteria**:
- [ ] Designs are up-to date
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by lewisdaly** [comment]
Given that we already are working on `POST /authorizations` in the existing transaction-requests-service, I think we should pick #1 for now, and worry about this later on.

**Comment by lewisdaly** [comment]
Michael: need to consider other areas that might be using this:
- e.g LPS adapter
- or other use cases down the line

**Comment by lewisdaly** [comment]
We went with #1 above, but this may be revisited at a later date.
