### ISSUE TITLE
mojaloop/pisp add contract tests to CI/CD pipeline

### ISSUE THREAD

**Issue by lewisdaly** [mojaloop/mojaloop#320]
## **Goal**:
As a `hub operator` 
I want to `have a CI/CD job for the pisp contract tests between the sdk-scheme-adapter and ml-testing toolkit` 
so `I can be sure of the consistency and quality of the PISP features`

This is building upon the work that will be completed in #302. That ticket ends with some manual steps to running the contract tests, and this ticket will be to automate those manual steps. It will look very similar to the `test-e2e` job in the current CI/CD Config: https://github.com/mojaloop/pisp/blob/master/.circleci/config.yml#L82

**Tasks**:
- [x] implement `test-contract` job in the CI/CD config
- [x] any readme/documentation updates for running/debugging contract tests locally

**Acceptance Criteria**:
- [x] new `test-contract` ci/cd job passing
- [x] updated documentation (if necessary)

## **Pull Requests**:
- [x] https://github.com/mojaloop/pisp/pull/27/

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
