### ISSUE TITLE
sdk-scheme-adapter: Handle transfer calls (Switch ➝ PISP)

### ISSUE THREAD

**Issue by lewisdaly** [mojaloop/mojaloop#321]
## **Goal**:
As a `PISP integrator` I want to `be able to handle PISP calls from the Switch in the scheme adapter` so that `implementation is easy and fun`

Refer to the [roles and endpoints list](https://github.com/mojaloop/pisp/blob/master/docs/roles_and_endpoints.md#thirdparty-api-switch---pisp)

**Tasks**:
- [x] Update local swagger definitions where required
- [x] Handle `POST /authorizations/`
- [x] Handle `PUT /thirdPartyRequest/transaction/{ID}`
- [x] Handle `PUT /thirdPartyRequest/transaction/{ID}/error`
- [x] new unit and integration tests where applicable
- [ ] ~~implementation will depend on the `mojaloop-simulator` scenario in order to complete integration tests.~~

```
testing topology:
pisp simulator <-> scheme adapter <-> mojaloop simulator (acting as a switch)
```

**Acceptance Criteria**:
- [x] Designs are up-to date
- [x] Unit Tests pass
- [x] Integration Tests pass
- [x] Code Style & Coverage meets standards

## **Pull Requests**:
- [x] https://github.com/mojaloop/sdk-scheme-adapter/pull/175
- [x] https://github.com/mojaloop/mojaloop-simulator/pull/56
## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
