### ISSUE TITLE
thirdparty-api-adapter health check

### ISSUE THREAD

**Issue by lewisdaly** [mojaloop/mojaloop#323]
## **Goal**:
As a `hub operator` I want to `have health checks running on the thirdparty-api-adapter` so that `I can be assured of the health of the service`.

Look at the central-ledger or ml-api-adapter implementations of the health check with the `central-services-health` library. For now add only kafka as a dependency, as we're sure that this service will at least need to talk to kafka.

We can use the auth-service as a starting point, which already has implemented the health checks.

**Tasks**:
- [x] implement a health check `/health` endpoint on the thirdparty-api-adapter
- [x] add necessary unit and integration tests
- [x] update the docker-compose config in `mojaloop/pisp` to use this health check, and the associated wait4 and wait4all scripts to aid test automation

**Acceptance Criteria**:
- [x] Unit Tests pass
- [x] Integration Tests pass
- [x] Any required updates to the `central-services-health` library
- [x] updated docker-compose config and passing e2e tests (no need to write new e2e tests, just make sure you don't break the existing ones
- [x] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
