### ISSUE TITLE
Update ml-api-adapter pisp image to latest version.

### ISSUE THREAD

**Issue by kleyow** [mojaloop/mojaloop#325]
## **Goal**:
As a developer I want to be building on the latest services to leverage the latest bug fixes and features.

**Tasks**:
- [ ] Update ml-api-adapter pisp/master branch to the latest tagged version build.

**Acceptance Criteria**:
- [ ] Updates are merged into pisp/master branch of the associated repository.
- [ ] Updated image is upgraded in mojaloop/pisp repo.
- [ ] Update any config needed to support new service version.
- [ ] Tests and build are successful

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
