### ISSUE TITLE
[Auth-Service + 3p-api-adapter] Automate Release

### ISSUE THREAD

**Issue by eoln** [mojaloop/mojaloop#329]
## **Goal**:
**As a** DevOps 
**I want to** automate the release 
**so that** I don't have to remember and do it manually

scope: auth-service && thirdparty-api-adapter
how to: https://medium.com/@kevinkreuzer/the-way-to-fully-automated-releases-in-open-source-projects-44c015f38fd6

**Tasks**:
- [x] add precommit hook to add conventional format check of the commit message (can always be skipped by --no-verify flag)
- [x] modify CircleCI config to run `npm run release` command and setup git access to allow push changes back to GitHub when PR is merged with the `master` (default branch)
- [x] what about GitHub releases?

**Acceptance Criteria**:
- [x] commits messages are checked
- [x] changelog is generated
- [x] new GitHub release is created automatically when PR is merged with the `master` (default branch)

## **Pull Requests**:
- [ ] TBD

**Comment by lewisdaly** [comment]
@eoln I was looking at this tool yesterday: https://semantic-release.gitbook.io/semantic-release/

Along with this [blog post](https://medium.com/@marcguilera/effective-meta-repo-ci-cd-pipelines-c18676443d) (not all will be applicable, but interesting stuff)

**Comment by kleyow** [comment]
https://github.com/mojaloop/rancher-scaler/blob/master/.circleci/config.yml

**Comment by eoln** [comment]
@lewisdaly I would stick to MVP version prepared by @kleyow

**Comment by eoln** [comment]
> @eoln I was looking at this tool yesterday: https://semantic-release.gitbook.io/semantic-release/
> 
> Along with this [blog post](https://medium.com/@marcguilera/effective-meta-repo-ci-cd-pipelines-c18676443d) (not all will be applicable, but interesting stuff)

that's really interesting stuff, I need to digest. In meantime let keep MVP solution prepared by @kleyow :-)

**Comment by lewisdaly** [comment]
Yeah the MVP on the rancher scaler is working quite well now (@kleyow there's a few updates from the example btw)

@kleyow the only trick to getting the release note uploading working is that we need to add the `mojaloopci` user to the github repos
