### ISSUE TITLE
sdk-scheme-adapter OutboundThirdpartyTransactionModel

### ISSUE THREAD

**Issue by lewisdaly** [mojaloop/mojaloop#331]
## **Goal**:
As a `PISP`
I want to `have a simple synchronous API to issue a 3rd party transaction request`
so that I `can easily implement and deliver value to my customer`

As described in the following design doc:
https://github.com/mojaloop/pisp/blob/master/docs/sdk_scheme_adapter_changes.md#outboundthirdpartytransactionmodel

> Models the PISP side of a PISP transaction, starting with a GET /parties, all the way to the PUT /thirdpartyRequests/transaction/{ID} callback.

**Tasks**:
- [ ] Implement the New OutboundThirdpartyTransactionModel using the current `sdk-scheme-adapter` state machine pattern
- [ ] New Unit tests
- [ ] Integration tests for interactions with the redis cache
> Contract and E2E tests will be covered elsewhere

**Acceptance Criteria**:
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by lewisdaly** [comment]
@eoln what is this a duplicate of?

**Comment by eoln** [comment]
@lewisdaly 
@kleyow said it is part of the story he is working on: https://app.zenhub.com/workspaces/pisp-5e8457b05580fb04a7fd4878/issues/mojaloop/mojaloop/314
