### ISSUE TITLE
thirdparty-scheme-adapter port InboundAuthorizationModel

### ISSUE THREAD

**Issue by lewisdaly** [mojaloop/mojaloop#333]
## **Goal**:
As a `DFSP`
I want to `have a simple synchronous API to issue be able to handle a 3rd party transaction request`
so that I `can easily implement and deliver value to my customer`

As described in the following design doc:
https://github.com/mojaloop/pisp/blob/master/docs/sdk_scheme_adapter_changes.md#inboundthirdpartytransactionmodel

> Models the DFSP side of a PISP transaction, initiated by receiving a `POST /thirdpartyRequests/transactions`

**Tasks**:
- [ ] port the InboundThirdPartyTransactionModel 
- [ ] refactor and tidy common code between other state machines where applicable
- [ ] New Unit tests
- [ ] Integration tests for interactions with the redis cache
> Contract and E2E tests will be covered elsewhere
- [ ] backend requests in `sdk-scheme-adapter`

**Acceptance Criteria**:
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by lewisdaly** [comment]
@eoln this may be out of scope now - please advise

**Comment by eoln** [comment]
It looks it is a duplicate of what @kleyow is working on
 https://app.zenhub.com/workspaces/pisp-5e8457b05580fb04a7fd4878/issues/mojaloop/mojaloop/314

**Comment by kleyow** [comment]
This is for inbound, which I am not handling. I'm working on the PISP outbound side https://github.com/mojaloop/pisp/blob/master/docs/sdk_scheme_adapter_changes.md#outboundthirdpartytransactionmodel

**Comment by eoln** [comment]
this work has been covered in #427
