### ISSUE TITLE
Improve test coverage of sdk-scheme-adapter `./src/lib/models`

### ISSUE THREAD

**Issue by lewisdaly** [mojaloop/mojaloop#336]
## **Goal**:
As a `OSS Maintainer` I want to `improve code coverage in the sdk-scheme-adapter` so that `we can eliminate tech debt, improve confidence in the scheme-adapter and allow us to refactor it.`

We want to refactor some common code in the scheme adapter, but before we do that, we need better test coverage to make sure we don't break things.

Note: this should be merged into `master`, not `pisp/master`.

**Tasks**:
- [ ] improve test coverage of `./src/lib/model` to 95% (it's currently around 64%)

**Acceptance Criteria**:
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards 

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
