### ISSUE TITLE
sdk-scheme-adapter: refactor common code

### ISSUE THREAD

**Issue by lewisdaly** [mojaloop/mojaloop#337]
## **Goal**:
As a `OSS maintainer` I want to `refactor common sdk-scheme-adapter code in the ./src/lib/model directory`so that `it is easier to contribute and extend the functionality`.

**Tasks**:
- [ ] refactor and tidy common code to keep separation of concerns between other state machines where applicable
- [ ] add documentation on how to create a new model for future implementers
- [ ] updated and new unit tests where applicable

**Acceptance Criteria**:
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Code Style & Coverage meets standards

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
