### ISSUE TITLE
Design: Consolidated updates for CCB

### ISSUE THREAD

**Issue by lewisdaly** [mojaloop/mojaloop#338]
## **Goal**:
As a `Michael`
I want to `update the CCB with the consolidated design docs` 
so that `we can deliver the benefits of PISP, while remaining aligned to the structure and objectives of the Mojaloop API`

**Tasks**:
- [ ] create CCB issue
- [ ] manage discussion at upcoming meeting
- [ ] report on successful results

**Acceptance Criteria**:
- [ ] everything we are doing is accepted by the CCB

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by lewisdaly** [comment]
We decided to scope this based on the SOW:

1. `POST /authorizations` - https://github.com/mojaloop/mojaloop-specification/pull/69
2. Account Linking - TBD
