### ISSUE TITLE
[auth-service] - handle signed credential - PUT /consents/{id}

### ISSUE THREAD

**Issue by lewisdaly** [mojaloop/mojaloop#340]
## **Goal**:
As a `DFSP`,
I want `to have a guarantee that my user signed the challenge from the auth-service`
so that `I can be confident that when I undertake other operations, it is with my user's consent`

auth-service perform validation on signed credential coming back in the `PUT /consents/{id}` from the PISP

1. handle the inbound `PUT /consents/{id}` request 
2. request validation
3. send back "202 OK"
4. validate the signed credential + publickey
>_error handling to be covered elsewhere_
5. update the credential status to `VERIFIED`
>_database/state to be handled in another story_
>_callbacks to DFSP/PISP to covered elsewhere_

**Tasks**:
- [x] implement the inbound `PUT /consents/{id}` handler
- [x] request validation on inbound request
- [x] validation of signed credential
- [x] update the credential status
- [x] new unit tests
- [ ] ~integration tests covering `PUT /consents/{id}` handling ??~ Handled in #368 

**Acceptance Criteria**:
- [ ] that when a user responds correctly with a `PUT /consents/{id}` the credential is marked as `VERIFIED`
- [x] incorrect response does not fulfil happy path
- [x] Unit Tests pass
- [ ] ~Integration Tests pass~
- [x] Code Style & Coverage meets standards

## **Pull Requests**:
- [ ] https://github.com/mojaloop/auth-service/pull/41

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by lewisdaly** [comment]
Is there a branch/fork for this?

**Comment by lewisdaly** [comment]
Ahan started on this, and has a draft PR. It needs a new owner.
