### ISSUE TITLE
Auth-Service: Persistence of Consents and Credentials

### ISSUE THREAD

**Issue by lewisdaly** [mojaloop/mojaloop#341]
## **Goal**:
As a `DFSP`, 
I want a `centralized auth-service to persist Consents along with associated public keys securely`,
so that `I can establish a user's identity`.

**Tasks**:
- [x] Database schema design for `Consents` and other associated tables
- [x] `Knex` library seeds and migrations to set up database
- [x] Models and CRUD implementation using knex library
- [x] Integration tests - running against in-memory SQLite database

**Acceptance Criteria**:
- [x] Database schema design document in `./docs/`
- [x] Unit Tests pass
- [x] Integration Tests pass
- [x] Code Style & Coverage meets standards
- [ ] TBD

## **Pull Requests**:
- [x] https://github.com/mojaloop/auth-service/pull/6
- [x] https://github.com/mojaloop/auth-service/pull/9 
- [x] https://github.com/mojaloop/auth-service/pull/10
- [x] https://github.com/mojaloop/auth-service/pull/12
- [x] https://github.com/mojaloop/auth-service/pull/18
- [x] https://github.com/mojaloop/auth-service/pull/21
## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by lewisdaly** [comment]
Hey @spikerheado1234 and @ramanmangla please add a link to your PR in the ticket above when you get a chance - thanks!
