### ISSUE TITLE
Auth-Service: POST /thirdpartyRequests/transactions/{id}/authorizations

### ISSUE THREAD

**Issue by lewisdaly** [mojaloop/mojaloop#342]
## **Goal**:
As a `DFSP`, 
I want `a centralized auth-service to verify signed transactions using POST /thirdpartyRequests/transactions/{id}/authorizations request`,
so that `I can verify user's transactions`.

![Screen Shot 2020-06-19 at 3.30.27 pm.png](https://images.zenhubusercontent.com/5cd963af3613073e20e46e60/6114f722-47a3-4cb1-89ac-7d36ec6657f6)

**Tasks**:
- [x] 1.handle inbound `POST /thirdpartyRequests/transactions/{id}/authorizations request`
- [x] 2.Basic request validation
- [x] 3.Respond with 202
- [x] 4.Lookup the `Consent` using the `Payload.consentId`
- [x] 5.Verify the `sourceAccountId` matches what is in the `Consent`
- [x] 6.Verify the `Payload.value` (signed Challenge) was indeed signed by the `Consent`'s publicKey
- [x] 7.Update OpenAPI specification for request schema
- [ ] 8.Unit tests:
  - [x] validating signatures
  - [x] request validation (null or empty fields)
  - [x] missing consent
  - [ ] integration tests

**Acceptance Criteria**:
- [x] Unit Tests pass
- [ ] Integration Tests pass
- [x] Code Style & Coverage meets standards

## **Pull Requests**:
- [x]  https://github.com/mojaloop/auth-service/pull/16
- [ ] https://github.com/mojaloop/auth-service/pull/22

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
