### ISSUE TITLE
Auth Service: Make a `Credential` immutable at a database level

### ISSUE THREAD

**Issue by lewisdaly** [mojaloop/mojaloop#343]
## **Goal**:
As a `DFSP`
I want `a guarantee that the consent credential saved by the auth service cannot be changed`
so that `I can be sure of a high level of security when issuing Transfers initiated by a PISP`

Enforce this constraint at a database level.

**Tasks**:
- [ ] Investigate implementation in `MySQL` and `Knex` (using database triggers)
- [ ] Implement trigger to throw error if any `non-null` field is updated
- [ ] Implement trigger to throw error if status is updated from 'ACTIVE` status
- [ ] Add tests to make sure the Credential is immutable, and attempts to update it fail

**Acceptance Criteria**:
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by ramanmangla** [comment]
- Researched through the documentation and online resources for consistent triggers between `MySQL` and `SQLite`
- Tried various implementations with almost consistent syntax
- Everything can be made consistent with some unconventional syntax except the different error throwing methods in both DBs
- Dropped the investigation and the ticket idea as the inconsistencies between testing and production would lead to more headache and confusion. Also, the transactional update provides similar functionality through model functions but not at a DB level.
