### ISSUE TITLE
Auth-Service: Local docker runner

### ISSUE THREAD

**Issue by lewisdaly** [mojaloop/mojaloop#344]
## **Goal**:
As a `OSS Developer`
I want `easy instructions to run the auth-service with database locally`
so that I can `easily test and verify the Auth-Service (manually)`.

Something like:
```
#run the database
docker-compose up -d mysql
# run the auth-service (locally)
npm run server
```

**Tasks**:
- [ ] Docker config for running local database (we have plenty of examples of this, or just ask @lewisdaly)
- [ ] Updated readme with examples

**Acceptance Criteria**:
- [ ] Designs are up-to date
- [ ] Code Style & Coverage meets standards

## **Pull Requests**:
- [ ] https://github.com/mojaloop/auth-service/pull/5

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
