### ISSUE TITLE
transaction-request-service: update pisp/master

### ISSUE THREAD

**Issue by eoln** [mojaloop/mojaloop#345]
## **Goal**:
As a Developer 
I want to merge master to pisp/master 
so that pisp/master is updated and the number of conflicts to resolve when pisp/master will be merged with the master is limited

Background: for transaction-request-service new release has been published so there is a need to update the pisp/master

scope of change of release: https://github.com/mojaloop/transaction-requests-service/releases/tag/v10.4.0

**Tasks**:
- [ ] merge master to pisp/master and resolve conflicts
- [ ] there is probably the need to do some refactor because of changes made to the master

**Acceptance Criteria**:
- [ ] Tests are not broken

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
