### ISSUE TITLE
[thirdparty-api-adapter] - handle `PUT /thirdpartyRequests/transactions/{id}/error`

### ISSUE THREAD

**Issue by lewisdaly** [mojaloop/mojaloop#346]
## **Goal**:
As a `DFSP` I want to `be able to inform a PISP of an error with a thirdparty request` so that `they can inform their user`.

**Tasks**:
in the PISP repo:
- [x] add new scenario to sequence diagrams, where a DFSP sends `PUT /thirdpartyRequests/transactions/{id}/error` to the  PISP
> e.g. if the `consentId` is invalid, or from the wrong PISP
> Document somewhere on this page: https://github.com/mojaloop/pisp/blob/master/docs/transfer/README.md

- [x] update api-snippets (if required) to include the error callback body
> Check with @kleyow , the master of the snippets

In the thirdparty-api-adapter:
- [x] add `PUT /thirdpartyRequests/transactions/{id}/error` to the [`api-template.yaml`](https://github.com/mojaloop/thirdparty-api-adapter/blob/master/src/interface/api-template.yaml) file
- [ ] handle inbound `PUT /thirdpartyRequests/transactions/{id}/error` from the DFSP
- [ ] respond to DFSP with a `200 OK`
- [ ] lookup the endpoint for the PISP based on the `FSPIOP-Destination` header
- [ ] forward request to PISP

- [ ] unit tests as required
> Note: don't worry about integration tests here

**Acceptance Criteria**:
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Code Style & Coverage meets standards

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by lewisdaly** [comment]
Let's not worry about failures at the moment, also this ticket should be broken down.
