### ISSUE TITLE
setup thirdparty-scheme-adapter repo

### ISSUE THREAD

**Issue by eoln** [mojaloop/mojaloop#347]
## **Goal**:
As a Dev 
I want to setup sdk-pisp-scheme-adapter repo
so that I can separate PISP related logic flow from DFSP only flow

reference repos: 
- https://github.com/mojaloop/auth-service
- https://github.com/mojaloop/sdk-scheme-adapter

migration of POST/PUT Authorizations code from sdk-scheme-adapter covered in another story

**Tasks**:
- [x] @mojaloop/api-snippets
- [x] OpenAPI Backend from `central-services-shared`
- [x] OpenAPI TS
- [x] Typescript types for dependencies in ambient.d.ts
- [x] Mozilla Convict as configuration manager
- [x] setup bdd test runner
- [x] setup relative paths shortcat
- [x] InboudServer: schema, handlers, unit tests
- [x] OutboundServer: schema, handlers, unit tests
- [x] CircleCI
- [x] Dockerization
- [x] docker-compose up` should run both servers and cache
- [x] integration-test run in CI/CD
- [x] refactor handlers layout
- [x] README && extend workflow tooling

**Acceptance Criteria**:
- [x] ability to independent run of Inbound/Outbound servers 
- [x] Typescript & @hapi
- [x] Unit Tests pass
- [x] Code Style & Coverage meets standards

## **Pull Requests**:
- [x] https://github.com/mojaloop/thirdparty-scheme-adapter/pull/1
- [x] https://github.com/mojaloop/thirdparty-scheme-adapter/pull/2
- [x] https://github.com/mojaloop/thirdparty-scheme-adapter/pull/3
- [x] https://github.com/mojaloop/thirdparty-scheme-adapter/pull/4
- [x] https://github.com/mojaloop/thirdparty-scheme-adapter/pull/5
- [x] https://github.com/mojaloop/thirdparty-scheme-adapter/pull/6
- [x] https://github.com/mojaloop/thirdparty-scheme-adapter/pull/7
- [x] https://github.com/mojaloop/thirdparty-scheme-adapter/pull/8
- [x] https://github.com/mojaloop/thirdparty-scheme-adapter/pull/9
- [x] https://github.com/mojaloop/thirdparty-scheme-adapter/pull/10/files

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by lewisdaly** [comment]
@eoln this is great - a couple questions:

1. Did we make a decision about where the "dfsp who wants to support PISP" functionality will live? Will that be _this_ repo? (I think it should be)
2. To keep naming consistent, I'd like this to be called `thirdparty-scheme-adapter`.

**Comment by eoln** [comment]
@lewisdaly I will rename. Shame on me I didn't see it. Here will be all DFSP/PISP related logic, also already existing POST /authorization extracted from sdk-scheme-adapter -> but extraction is in other story
