### ISSUE TITLE
[thirdparty-scheme-adapter] - integration tests for authorizations

### ISSUE THREAD

**Issue by eoln** [mojaloop/mojaloop#349]
## **Goal**:
As a Dev 
I want to have integration tests
so that I am sure the whole setup is working well

**Tasks**:
- [x] setup docker-compose config to run 
- [x] test: outbound POST /authorizations - MojaloopSimulator](https://github.com/mojaloop/mojaloop-simulator) to simulate handling `POST /authorization` from OutboundServer and calling `PUT /authorization{id}` with the signed condition on InboundServer
- [x] test: inbound POST /authorizations - Implement condition signing in mojaloop-simulator upon receiving `POST /authorization` at Inbound

> Note: We can borrow docker-compose config from `mojaloop/pisp/docker-local/docker-compose.yml`
> Note: CI/CD will be covered elsewhere
> Note: test cases are already implemented [here](https://github.com/mojaloop/pisp/blob/master/test/e2e/PIPSAuthorizations.test.ts), we just need to replace sdk-scheme-adapter with thirdparty-scheme-adapter

**Acceptance Criteria**:
- [ ] local Integration Tests pass
- [ ] Code Style & Coverage meets standards

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by lewisdaly** [comment]
@eoln in our discussions, we were wondering why use the MockedDFSPBackend instead of just the simluator

**Comment by eoln** [comment]
MockedDFSPBAckend is a reference service to do integration tests with scheme-adapter. It contains also examples for DFSP integrators how integration with scheme-adapter could look like without introducing the concept of mojaloop_simulator or ml_testing_toolkit.

**Comment by lewisdaly** [comment]
We will know more about this after we have finished the migration of #348

**Comment by eoln** [comment]
https://github.com/mojaloop/pisp/blob/master/test/e2e/PIPSAuthorizations.test.ts
![components_layout.png](https://images.zenhubusercontent.com/5e9efb1f861fca3041741b8a/30d9b7e2-425b-4948-a94e-4b99c91c681f)

**Comment by lewisdaly** [comment]
Great work @chbhernani and @eoln !
