### ISSUE TITLE
[sdk-mock-dfsp-backend] - handle `POST /authorization`

### ISSUE THREAD

**Issue by eoln** [mojaloop/mojaloop#350]
## **Goal**:
As a Dev 
I want the [sdk-mock-dfsp-backend](https://github.com/mojaloop/sdk-mock-dfsp-backend) to initiate `POST /authorization` call on thirdparty-scheme-adapter
so that I can test the integration

**Tasks**:
- [ ] add `POST /authorization` path to trigger/forward the call to `thirdparty-scheme-adapter` from the test runner
- [ ] add unit tests
- [ ] integration tests are covered in another story #349

**Acceptance Criteria**:
- [ ] Unit Tests pass
- [ ] Code Style & Coverage meets standards

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by kleyow** [comment]
Why `sdk-mock-dfsp-backend`? Isn't `mojaloop-simulator` what we should use for our FSP simulation needs?

**Comment by eoln** [comment]
`sdk-mock-dfsp-backend` is a very simplified, dedicated to skd-scheme-adapter only, mocked DFSP backend so the entry-level for DFSP for integration is very low. Of course, we can use ml-testing-toolkit instead. I marked it nice-to-have and let use ml-testing-toolkit instead of sdk-mock-dfsp-backend, what should be a faster path...

**Comment by lewisdaly** [comment]
Closing for now as I think this is out of scope. Please reopen if I'm wrong.
