### ISSUE TITLE
[auth-service] - Update to OpenAPI v3

### ISSUE THREAD

**Issue by lewisdaly** [mojaloop/mojaloop#352]
## **Goal**:
As an `OSS developer`
I want `the auth service to be updated from swagger 2 to 3`
so that `I can better support user's needs and improve maintainability`

**Tasks**:
- [ ] convert the existing auth service swagger spec to use the mojaloop/api-snippets library (this is mostly done, ask @lewisdaly about it)
- [ ] replace `hapi-openapi` with the `openapi-backend` plugin we are starting to adopt across mojaloop
- [ ] address swagger generated routes - `openapi-backend` doesn't make nice routes for us, which means that the tooling we use (`hapi-swagger` no longer displays all of our routes nicely)
    - perhaps one option here would be to not use `hapi-swagger` to generate yet _another_ swagger file from our hapi server, but instead serve the swagger file we have 

**Acceptance Criteria**:
- [ ] Updated swagger templates and snippets to v3.0
- [ ] viable full replacement for `hapi-openapi` implemented
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by lewisdaly** [comment]
This should be much easier now that we've done it a few times.

**Comment by lewisdaly** [comment]
This has been done.
