### ISSUE TITLE
[auth-service] - End-to-End BDD Testing for Endpoints

### ISSUE THREAD

**Issue by ramanmangla** [mojaloop/mojaloop#354]
## **Goal**:
As an `OSS Developer`
I want to `create end-to-end behavior driven tests for the auth-service end points`
so that `I can ensure that the service correctly functions for all user interactions.`

**Tasks**:
- [ ] Tests targeting Consent and Scope models
- [ ] Implement 'jest side` BDD tests for the existing Gherkin for 
  > Refer to: https://github.com/mojaloop/auth-service/blob/master/test/features/linking.scenario.feature
  > Note: if you find missing test cases, please open a follow up ticket

**Acceptance Criteria**:
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by ramanmangla** [comment]
## **Goal**:
As a `Developer`
I want `create end-to-end behavior driven tests for the auth-service end points`
so that `I can ensure that the service correctly functions for all user interactions.`

**Tasks**:
- [ ]
- [ ]
- [ ] 

**Acceptance Criteria**:
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by lewisdaly** [comment]
Issue moved to [mojaloop/project #1820](https://github.com/mojaloop/project/issues/1820) via [**ZenHub**](https://www.zenhub.com/)
