### ISSUE TITLE
[auth-service] - Consistent Error Handling for `PUT callbacks`

### ISSUE THREAD

**Issue by ramanmangla** [mojaloop/mojaloop#355]
## **Goal**:
As a `Developer`
I want `ensure consistent and complete error handling in auth models and endpoints`
so that `I can ensure there is no undefined behavior at run time.`

**Tasks**:
- [ ] Add Auth-Service/PISP specific errors to the Mojaloop error codes
- [x] Modify sdk-standard-components to be able to call `PUT consents/{ID}/error` to notify the client of an error in the auth-service
- [x] Modify auth-service source code to handle errors correctly
- [x] Add unit tests to test `PUT callback` errors
~- [ ] Add integration tests to test `PUT callback` error API flows~
- [ ] Document error conditions for later refining and mapping to approved error codes

**Acceptance Criteria**:
- [ ] Unit tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards

## **Pull Requests**:
- [x] https://github.com/mojaloop/sdk-standard-components/pull/108

## **Follow-up**:
- [ ] Harmonize error codes afterwards

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by eoln** [comment]
The idea behind this story is that all handling of async errors reported to the client using PUT …/{id}/error should be handled in the same way/style over the code. Now in code, there are still places with TODO comments and there is a need to revise the whole code and make it consistent.

There is also a need to revise the list of error codes and create a new one if needed

**Comment by lewisdaly** [comment]
Issue moved to [mojaloop/project #1815](https://github.com/mojaloop/project/issues/1815) via [**ZenHub**](https://www.zenhub.com/)
