### ISSUE TITLE
Auth-Service: docker-compose integration tests

### ISSUE THREAD

**Issue by lewisdaly** [mojaloop/mojaloop#357]
## **Goal**:
As a `OSS Developer`
I want to have `working integration tests set up and an example integration test`
so that `it's easy to write new integration tests`

**Tasks**:
- [x] docker compose environment
- [ ] simple instructions in readme.md
- [x] example integration test
- [x] passing tests on circleci

**Acceptance Criteria**:
- [x] working integration test runner and example as above
- [x] Integration Tests pass
- [ ] TBD

## **Pull Requests**:
- [ ] https://github.com/mojaloop/auth-service/pull/25

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by lewisdaly** [comment]
I think this was somewhat covered in #278 - but the integration tests don't use the docker containers.

**Comment by lewisdaly** [comment]
using branch: `feature/357-integration-test-runner`
