### ISSUE TITLE
Auth-Service: Issue `PUT /thirdpartyRequests/transactions/{id}/authorizations` (Auth-Service -> Switch)

### ISSUE THREAD

**Issue by lewisdaly** [mojaloop/mojaloop#358]
## **Goal**:
As a `DFSP`
I want `to be informed of an authorization result`
so I `know if I can proceed with a third party transaction`

**Tasks**:
- [x] Implement the `PUT /thirdpartyRequests/transactions/{id}/authorizations` call from the Auth-Service -> Switch
**Acceptance Criteria**:
- [x] Designs are up-to date
- [x] Unit Tests pass
- [x] Integration Tests pass
- [x] Code Style & Coverage meets standards

## **Pull Requests**:
- [ ] https://github.com/mojaloop/auth-service/pull/22

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
