### ISSUE TITLE
Transaction-Request-Service: Update `PUT /authorizations/{id}` for U2F

### ISSUE THREAD

**Issue by lewisdaly** [mojaloop/mojaloop#359]
## **Goal**:
As a `PISP`
I want to `be able to send a PUT /authorizations/{id} callback to the DFSP`
so that `I can prove that my customer approved the transaction`.

At the moment, when we issue a `PUT /authorizations/{id}` with the new format, the `transaction-request-service` rejects request with a validation error:

**Example request**
```
curl --location --request PUT 'localhost:4003/authorizations/123' \
--header 'Accept: application/vnd.interoperability.authorizations+json;version=1' \
--header 'Content-Type: application/vnd.interoperability.authorizations+json;version=1.0' \
--header 'fspiop-source: payerfsp' \
--header 'fspiop-destination: payeefsp' \
--header 'fspiop-signature: {"signature":"iU4GBXSfY8twZMj1zXX1CTe3LDO8Zvgui53icrriBxCUF_wltQmnjgWLWI4ZUEueVeOeTbDPBZazpBWYvBYpl5WJSUoXi14nVlangcsmu2vYkQUPmHtjOW-yb2ng6_aPfwd7oHLWrWzcsjTF-S4dW7GZRPHEbY_qCOhEwmmMOnE1FWF1OLvP0dM0r4y7FlnrZNhmuVIFhk_pMbEC44rtQmMFv4pm4EVGqmIm3eyXz0GkX8q_O1kGBoyIeV_P6RRcZ0nL6YUVMhPFSLJo6CIhL2zPm54Qdl2nVzDFWn_shVyV0Cl5vpcMJxJ--O_Zcbmpv6lxqDdygTC782Ob3CNMvg\",\"protectedHeader\":\"eyJhbGciOiJSUzI1NiIsIkZTUElPUC1VUkkiOiIvdHJhbnNmZXJzIiwiRlNQSU9QLUhUVFAtTWV0aG9kIjoiUE9TVCIsIkZTUElPUC1Tb3VyY2UiOiJPTUwiLCJGU1BJT1AtRGVzdGluYXRpb24iOiJNVE5Nb2JpbGVNb25leSIsIkRhdGUiOiIifQ"}' \
--header 'fspiop-uri: /transactionRequests' \
--header 'fspiop-http-method: PUT' \
--data-raw '{
    "authenticationInfo": {
        "authentication":"U2F",
        "authenticationValue": {
            "pinValue": "12345",
            "counter": "1"
        },
        "responseType": "ENTERED"
    }
}'
```

**Response**
```json
{
    "errorInformation": {
        "errorCode": "3101",
        "errorDescription": "Malformed syntax - .requestBody.authenticationInfo.authenticationValue should be string"
    }
}
```

As this is a pisp only change, this should be merged into the `pisp/master` of `transaction-request-service`

**Tasks**:
- [x] update the `tx-request-service` swagger definition for U2F authorization (maybe use API Snippets?)
- [x] handle the new inbound `PUT /authorizations/{id}` (this may just be as simple as updating the swagger spec) - implement additional validation to check `authenticationValue` field has proper format depending on `authentication` property value
- [x] call the outbound `PUT /authorizations/{id}` 
- [x] Integration tests for regression to make sure we don't break the existing functionality
- [x] Integration tests for `PUT /authorizations/{id}` with new format
- [x] unit tests as needed

**Acceptance Criteria**:
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards

## **Pull Requests**:
- [x] https://github.com/mojaloop/transaction-requests-service/pull/48

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by eoln** [comment]
I updated tx-request-service yaml, modified the handler and currently, the change is merged to  pisp/master.

**Comment by eoln** [comment]
For the request the`authenticationValue` property type should be an `object` when `authentication` is `U2F` and `string` elsewhere. This logic isn't handled by swagger validation plugin so it should be done by additional code in PUT handler
