### ISSUE TITLE
SDK-Standard-Components: `PUT /consents/{id}`

### ISSUE THREAD

**Issue by lewisdaly** [mojaloop/mojaloop#360]
## **Goal**:
As a `PISP`
I want `an easy way to issue PUT /consents/{id} requests`
to make `integration with a mojaloop switch fun and easy`

**Tasks**:
- [x] Add new `PUT /consents/{id}` call to `thirdPartyRequests.js`
- [x] unit tests
- [x] update any required documentation
- [x] is it possible to add typescript types here?
- [x] update package
- [x] deploy updated `sdk-standard-components`

**Acceptance Criteria**:
- [ ] Unit Tests pass
- [x] updated documentation
- [ ] new published release for sdk-standard-components
- [ ] Code Style & Coverage meets standards

## **Pull Requests**:
- [x] https://github.com/mojaloop/sdk-standard-components/pull/71

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
