### ISSUE TITLE
[auth-service] - Make JWS and TLS configurable

### ISSUE THREAD

**Issue by akapur99** [mojaloop/mojaloop#361]
## **Goal**:
As a `Hub Operator/DFSP`
I want to `be able to configure TLS and JWS`
so that `my requests are signed correctly per the mojaloop standard`

**Tasks**:
- [x] Expose JWS signing config
- [ ] Expose mutualTLS config
- [x] update `default.json` and descriptions
- [x] add demo secret keys and config (these can be copied from sdk-scheme-adapter library)
- [ ] unit tests on config parser - ensure that config is parsed and applied correctly
- [ ] add the endpoint config to configure the switch base url(s) see [here](https://github.com/mojaloop/thirdparty-scheme-adapter/blob/master/config/development.json#L28) and [here](https://github.com/mojaloop/thirdparty-scheme-adapter/pull/14/files) for reference.

**Acceptance Criteria**:
- [ ] Unit Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] https://github.com/mojaloop/auth-service/pull/49/

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by lewisdaly** [comment]
@kkzeng this might be good to look at.

**Comment by akapur99** [comment]
Left to do:
* Tests
* Figuring whether we need to be sending tls credentials as well (I believe we can use the pem files in the secrets folder set up)
* Check whether the method of reading in the jws signing key is correct - it's copied from sdk-scheme-adapter but i have a feeling it's wrong 
* Enabling jws sign and tls (this just entails flipping the boolean value in the default.json, once we feel its ready)
