### ISSUE TITLE
Auth-Service Integration Testing

### ISSUE THREAD

**Issue by spikerheado1234** [mojaloop/mojaloop#368]
## **Goal**:
As an `OSS maintainer`,
I want to ensure that `different parts of the auth-service interact with each other as expected`,
so that I can ensure a `highly tested and robust auth-service`. 

**Tasks**:
- [x] Integration tests for seeds.
- [x] Integration tests for all models
- [x] Integration tests for all domains
- [x] Integration tests for all handlers (202 Accepted response)
~- [ ] Integration tests for all handlers (Async domain processing for error-free flow - use mojaloop testing toolkit)~
~- [ ] Update OpenAPI specification (Major revisions being addressed in #412)~
- [x] Modify jest config `collectCoverage: false`
- [x] Modify Dockerfile, wait4.js and CI config to build and run auth-service

**Acceptance Criteria**:
- [x] Integration Tests pass
- [x] Code Style & Coverage meets standards

## **Pull Requests**:
- [x] https://github.com/mojaloop/auth-service/pull/34
- [x] https://github.com/mojaloop/auth-service/pull/48

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by ramanmangla** [comment]
- Have an open PR#36 on the auth-service with
  - 202 accepted response integration tests for merged in handlers
  - docker-compose setup for handler integration testing
- Need to update auth-service to use openapi-backend plugin to proceed
  - Current OpenAPI plugin does not work for nested routes with .ts extensions eg. thirdpartyRequest/transactions/{ID}
  - This is why the open PR#36 fails tests
- Need to update OpenAPI specification for consistent API definitions beofre testing handlers
