### ISSUE TITLE
Auth-Service: Replace Relative Paths for Imports

### ISSUE THREAD

**Issue by akapur99** [mojaloop/mojaloop#369]
## **Goal**:
As an `OSS Developer`
I want to `add support for shorter absolute import paths`
so that `importing files is easier and code lines are shorter`.

E.g: `../../../../src/lib/requests` -> `~/lib/requests`

**Tasks**:
- [x] Modify Jest config
- [x] Modify TypeScript config
- [x] Modify ESLint config
- [x] Modify `package.json`
- [x] Replace all relative paths with new implementation

**Acceptance Criteria**:
- [x] Unit Tests pass
- [x] Integration Tests pass
- [x] Code Style & Coverage meets standards

## **Pull Requests**:
- [ ] https://github.com/mojaloop/auth-service/pull/29

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by lewisdaly** [comment]
@ramanmangla @akapur99 is this in progress?
