### ISSUE TITLE
[api-snippets] - Create pisp super set of api-snippets.

### ISSUE THREAD

**Issue by kleyow** [mojaloop/mojaloop#370]
## **Goal**:
As a developer I want to have a singular reference for definitions and schema's being developed for PISP functionality so that service API interfaces are aligned, to avoid duplication and confusion.

**Tasks**:
- [ ] Create `v1.1-thirdparty` folder in `api-snippets`
- [ ] Add `npm run` command to bundle and validate `v1.1-thirdparty` spec

**Acceptance Criteria**:
- [ ] Bundling command added and works.
- [ ] Folder create and files copied over.

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
