### ISSUE TITLE
[api-snippets] - Import various pisp specific responses, requests and schema definitions from mojaloop/pisp

### ISSUE THREAD

**Issue by kleyow** [mojaloop/mojaloop#371]
## **Goal**:
As a developer I want to move schemas and definitions to the api-snippets library so that the information is consolidated into one place for use by many services.

**Tasks**:
- [ ] PISP specific definitions are moved over to `api-snippets` repository (if any)
- [ ] PISP specific resources/definitions/schema snippets are denoted as PISP specific in the definition.

**Acceptance Criteria**:
- [ ] Snippets are imported from `mojaloop/pisp`
- [ ] `thirdparty` snippets and bundled and validated using `npm run build:thirdparty` in the api snippets
- [ ] reviewed by more than 1 reviewer (one from auth-service, 3p-api-adapter)

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by kleyow** [comment]
Don't believe the mojaloop/pisp repo has any snippets to extract. Closing.
