### ISSUE TITLE
[api-snippets] - Import various pisp specific responses, requests and schema definitions from mojaloop/auth-service

### ISSUE THREAD

**Issue by kleyow** [mojaloop/mojaloop#372]
## **Goal**:
As a developer I want to move schema and definitions to the api-snippets library so that the information is consolidated into one place for use by many services.

**Tasks**:
- [ ] PISP specific definitions are moved over to `api-snippets` repository.
- [ ] PISP specific resources/definitions/schema snippets are denoted as PISP specific in the definition.

**Acceptance Criteria**:
- [ ] Snippets are imported from mojaloop/auth-service.
- [ ] `v1.1-pisp` snippets and bundled and validated using `npm run buildv1.1-pisp`

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
