### ISSUE TITLE
Add typescript definitions for v1.1-pisp snippets in api-snippets library.

### ISSUE THREAD

**Issue by kleyow** [mojaloop/mojaloop#374]
## **Goal**:
As a developer I want to leverage api-snippet's maintainability, portability and single source of truth for typescript definitions so that definitions can be integrated with services very quickly.

**Tasks**:
- [ ] Investigate open api to typescript definition translators
- [ ] Added typescript definitions for v1.1-pisp schema.

**Acceptance Criteria**:
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by lewisdaly** [comment]
@kleyow I think this is a good idea, but I do worry about code maintainability across repos and separation of concerns here. 

For example, if I want to make a minor change to the `sdk-standard-components` library's type definitions, but that library uses some type definitions from api-snippets, then we could be creating a whole lot of work for us.

**Comment by kleyow** [comment]
Ok.
