### ISSUE TITLE
pisp-demo-server: implement party lookup for the transfer flow

### ISSUE THREAD

**Issue by stevenwjy** [mojaloop/mojaloop#375]
## **Goal**:
**As a** `PISP` 
**I want to** `lookup information about a payee`
**so that** `my user can be sure that the payee is correct`

**Tasks**:
- [x] Setup communication with Firebase
- [x] Define interface models that will be used throughout this process
- [x] Generate `transactionRequestId` and update status for new transaction
- [x] Perform `GET /parties/{Type}/{ID}` request to Mojaloop (mocked)
- [x] Listen to callback `PUT /parties/{Type}/{ID}` from Mojaloop (mocked)
- [x] Update Firebase upon receiving callback from Mojaloop

**Acceptance Criteria**:
- [x] Designs are up-to date
- [x] Unit Tests pass
- [x] Code Style & Coverage meets standards 

## **Pull Requests**:
- [x] https://github.com/mojaloop/pisp-demo-server/pull/7/files

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
