### ISSUE TITLE
pisp-demo-server: implement payee confirmation and authorization prompt

### ISSUE THREAD

**Issue by stevenwjy** [mojaloop/mojaloop#376]
## **Goal**:
**As a** `PISP`
**I want to** `initiate a transaction after the user confirms the payee`
**so that** `users can send their money using my app`

**Tasks**:
- [x] Handle payee confirmation event from Firebase
- [x] Initiate a transaction to Mojaloop using `POST /thirdpartyRequests/transactions`
- [x] Handle callback from Mojaloop for authorization prompt (i.e., `POST /authorizations`)
- [x] Update Firebase to notify the user about the authorization prompt

**Acceptance Criteria**:
- [x] Designs are up-to date
- [x] Unit Tests pass
- [x] Code Style & Coverage meets standards

## **Pull Requests**:
- [x] https://github.com/mojaloop/pisp-demo-server/pull/8

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
