### ISSUE TITLE
Refactor the existing app codebase to use Getx

### ISSUE THREAD

**Issue by MahidharBandaru** [mojaloop/mojaloop#378]
## **Goal**:
As a developer I want the Mojapay codebase to have a well defined architecture with good separation of ui and business logic.

**Tasks**:
- [x] Refactor auth, landing and profile screens.
- [x] Refactor accounts dashboard
- [x] Refactor transaction flow

**Acceptance Criteria**:
- [x] The codebase follows MVVM architecture.
- [ ] Code Style & Coverage meets standards

## **Pull Requests**:
- [x] https://github.com/mojaloop/pisp-demo-app-flutter/pull/9
- [x] https://github.com/mojaloop/pisp-demo-app-flutter/pull/11
- [ ] https://github.com/mojaloop/pisp-demo-app-flutter/pull/12
