### ISSUE TITLE
pisp-demo-server: communicate with Mojaloop to perform requests for the transfer flow

### ISSUE THREAD

**Issue by stevenwjy** [mojaloop/mojaloop#379]
## **Goal**:
**As a** `PISP` 
**I want to** `communicate with Mojaloop to perform party lookup`
**so that** `I can be sure that all of the information are correct`

**Tasks**:
- [ ] Register URL of the PISP demo server in Mojaloop to receive callbacks
- [ ] Make `GET /parties/{Type}/{ID}` request to Mojaloop
- [ ] Make `POST /thirdpartyRequests/transactions` request to Mojaloop
- [ ] Make `PUT /authorizations/{ID}` request to Mojaloop

**Acceptance Criteria**:
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Code Style & Coverage meets standards

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by lewisdaly** [comment]
@stevenwjy to break this one down further
