### ISSUE TITLE
Integrate the Mojapay app with PISP server backend and mock end to end transaction

### ISSUE THREAD

**Issue by MahidharBandaru** [mojaloop/mojaloop#380]
## **Goal**:
As a payer I want to send money to a payee using the mojapay app.

**Tasks**:
- [x] Connect mojapay to firebase and implement transaction flow as defined in the transfer sequence diagrams.
- [x] Add dummy data for linked user accounts to firebase for a test user
- [x] Simulate end to end flow with PISP demo server

**Acceptance Criteria**:
- [x] The app can be used to send money end to end.
- [ ] Code Style & Coverage meets standards

## **Pull Requests**:
- [ ] https://github.com/mojaloop/pisp-demo-app-flutter/pull/17
