### ISSUE TITLE
Design Docs for Mojapay

### ISSUE THREAD

**Issue by MahidharBandaru** [mojaloop/mojaloop#381]
## **Goal**:
As a developer I want to onboard faster onto Mojapay by referring to the design docs.

**Tasks**:'
- [x] Write doc showing design screenshots and navigation flow
- [x] Write doc explaining architecture
- [x] Write doc explaining firebase schema
- [x] Write doc explaining auth business logic
- [x] Write doc explaining transaction flow business logic
- [x] Write doc explaining account dashboard business logic
- [x] Write doc explaining procedure to add new features to Mojapay.

**Pull Requests**:
- [x] https://github.com/mojaloop/pisp-demo-app-flutter/pull/25

**Acceptance Criteria**:
- [ ] Designs are up-to date

**Comment by lewisdaly** [comment]
Looks like the PR for this is merged. @kkzeng can this be moved to done?

**Comment by kkzeng** [comment]
Yes, I believe Madhihar said that he had finished the docs.
