### ISSUE TITLE
[auth-service] - Unlinking API Sequence and Endpoints

### ISSUE THREAD

**Issue by ramanmangla** [mojaloop/mojaloop#382]
## **Goal**:
As a `PISP` 
I want to `unlink my consent and associated credentials` 
so that `I can unregister a device/account from the auth-service`

**Tasks**:
- [ ] API Sequence Diagram
- [ ] Unlinking Incoming handler from `switch`
- [ ] Outgoing request to notify the `switch` of success/failure
- [ ] Delete `consent` and `scopes` from the Auth DB

**Acceptance Criteria**:
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by lewisdaly** [comment]
@ramanmangla I feel like some of this work is being covered elsewhere... can you please check and update this ticket?

**Comment by lewisdaly** [comment]
Duplicate of https://github.com/mojaloop/mojaloop/issues/384
