### ISSUE TITLE
Unit testing for Mojapay

### ISSUE THREAD

**Issue by MahidharBandaru** [mojaloop/mojaloop#385]
## **Goal**:
As a developer I want good unit test coverage in mojapay code base

**Tasks**:
- [x] Write unit tests for authentication business logic.
- [x] Write unit tests for transaction flow business logic.
- [x] Write unit tests for accounts dashboard business logic.
- [ ] Write unit tests for firebase integration

**Acceptance Criteria**:
- [ ] Unit Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by lewisdaly** [comment]
@stevenwjy please follow up and close if applicable
