### ISSUE TITLE
SDK-Standard-Components: `PUT /thirdpartyRequests/transactions/{ID}/authorizations/error` Method

### ISSUE THREAD

**Issue by ramanmangla** [mojaloop/mojaloop#386]
## **Goal**:
As an `auth-service`
I want `an easy way to issue PUT /thirdpartyRequests/transactions/{ID}/authorizations/error`
to `notify other participants about errors`

**Tasks**:
- [x] Add new `PUT /thirdpartyRequests/transactions/{ID}/authorizations/error` call to `thirdPartyRequests.js`
- [x] unit tests
- [x] update package
- [x] deploy updated `sdk-standard-components`

**Acceptance Criteria**:
- [x] Unit Tests pass
- [x] updated documentation
- [x] new published release for sdk-standard-components
- [x] Code Style & Coverage meets standards

## **Pull Requests**:
- [x] https://github.com/mojaloop/sdk-standard-components/pull/84

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
