### ISSUE TITLE
[auth-service] - consistent config

### ISSUE THREAD

**Issue by eoln** [mojaloop/mojaloop#388]
**Summary**:
Config is declared in more than one place, sometimes using RC, sometimes using Convict
https://github.com/mojaloop/auth-service/blob/master/src/lib/config.ts
https://github.com/mojaloop/auth-service/blob/master/src/shared/config.ts

**Severity**:
(Low)

**Priority**:
(Medium)

**Expected Behavior**
To have one config to rule them all, in src/shared/config.ts

**Tasks**:
- [x] Replace RC with Convict
- [x] Merge multiple configs into a master config
- [x] Define Convict Config definition for validation
- [x] Auto-load config for dev, test and prod environments based on NODE_ENV
- [ ] Auto-migrate DB after connection setup (Add commands in Dockerfile)
- [x] Refactor files to work with new config

**Acceptance Criteria**:
- [ ] Integration Tests pass
- [x] Unit Tests Pass

## **Pull Requests**:
- [ ] https://github.com/mojaloop/auth-service/pull/37

**Comment by eoln** [comment]
pending PR: https://github.com/mojaloop/auth-service/pull/37

**Comment by lewisdaly** [comment]
@kkzeng this might be good to look at.
