### ISSUE TITLE
[auth-service] - Update to use mojaloop/api-snippets

### ISSUE THREAD

**Issue by kleyow** [mojaloop/mojaloop#390]
## **Goal**:
As a developer I want to use api-snippets for open api schemas so that leverage it's maintainability and one source of truth-ness.

**Tasks**:
- [x] Update any interfaces in service to use api-snippets.
- [x] upgrade to `openapi-backend` (since the api-snippets use OAS/Swagger v3)

**Acceptance Criteria**:
- [x] Designs are up-to date
- [x] Tests pass

## **Pull Requests**:
- [x] https://github.com/mojaloop/auth-service/pull/44

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
