### ISSUE TITLE
Account linking: Consent request and authentication

### ISSUE THREAD

**Issue by kkzeng** [mojaloop/mojaloop#397]
**Goals**
- As a user, I want to able to choose a financial provider that I use and link my account. I want to be able to see the permissions I'm granting the app.

This covers the following stages of Account Linking:
- Consent Request
- Authentication Prompt
- Authentication

**Task**
- [x] Use ConsentRepository to update the relevant data in Firebase to request Consent - auth channel + account list (Based on what user has selected)
- [x] For Web auth, read "authUri" and redirect the user to the provided URL in a webview.
- [x] For Web auth, extract authToken when FSP login redirects user.
- [x] For OTP auth, open OTP screen and prompt user to enter a OTP.
- [x] Return an authToken proving the user trusts the PISP app.
- [x] Manually test web flow with a simple website
- [x] Manually test OTP flow by verifying auth token is updated in Firebase
