### ISSUE TITLE
[demo-app] - linking Request and sign challenge

### ISSUE THREAD

**Issue by kkzeng** [mojaloop/mojaloop#399]
**Goals**

**Task**

- [ ] Request a challenge from the backend
- [ ] Ask user to verify identity using biometric auth process (fallback to PIN if not available)
- [ ] Sign the challenge
- [ ] Show that account linking process was successful using a nice UI.

**Comment by lewisdaly** [comment]
Issue moved to [mojaloop/project #1813](https://github.com/mojaloop/project/issues/1813) via [**ZenHub**](https://www.zenhub.com/)
