### ISSUE TITLE
pisp-demo-server: Register Mojaloop Callback URL and Setup sdk wrapper

### ISSUE THREAD

**Issue by stevenwjy** [mojaloop/mojaloop#401]
## **Goal**:
**As a** `PISP` 
**I want to** `register my URL`
**so that** `Mojaloop can make callbacks to the URL that I have registered`

**Tasks**:
- [x] Setup a wrapper for `sdk-standard-components` to make a request to Mojaloop 
- [ ] Register URLs of the PISP demo server in Mojaloop
- [ ] Ensure that PISP demo server could receive callbacks from Mojaloop

**Acceptance Criteria**:
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Code Style & Coverage meets standards

## **Pull Requests**:
- [x] https://github.com/mojaloop/pisp-demo-server/pull/13
- [x] https://github.com/mojaloop/pisp-demo-server/pull/14

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by lewisdaly** [comment]
@kkzeng to follow up steven and find out where this is at.
