### ISSUE TITLE
pisp-demo-server: Implement request for party lookup to Mojaloop

### ISSUE THREAD

**Issue by stevenwjy** [mojaloop/mojaloop#402]
## **Goal**:
**As a** `PISP`
**I want to** `make party lookup requests to Mojaloop`
**so that** `I can get more information about the requested parties`

**Tasks**:
- [ ] Make `GET /parties/{Type}/{ID}` request to Mojaloop
- [ ] Ensure that the PISP demo server can receive `PUT /paties/{Type}/{ID}` callback from Mojaloop

**Acceptance Criteria**:
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Code Style & Coverage meets standards

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by lewisdaly** [comment]
Closing as we have implemented some of this, and will be reevaluating this implementation shortly.
