### ISSUE TITLE
Widget testing for Mojapay

### ISSUE THREAD

**Issue by MahidharBandaru** [mojaloop/mojaloop#405]
## **Goal**:
As a developer I want Mojapay to have good widget testing coverage.

**Tasks**:
- [x] Write widget tests for authentication screens
- [ ] Write widget tests for transaction flow screens
- [ ] Write widget tests for account dashboard screen

**Acceptance Criteria**:
- [ ] Designs are up-to date
- [ ] Widget Tests Pass

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by lewisdaly** [comment]
Issue moved to [mojaloop/project #1812](https://github.com/mojaloop/project/issues/1812) via [**ZenHub**](https://www.zenhub.com/)
