### ISSUE TITLE
Produce a list of endpoints and endpoint templates for PISPs and DFSPs to register

### ISSUE THREAD

**Issue by lewisdaly** [mojaloop/mojaloop#408]
## **Goal**:
As a `DFSP/PISP`
I want to `be able to register PISP related endpoints`
so I `can add PISP functionality`

**Tasks**:
- [x] produce a list of all of the new endpoints and endpoint templates that need to be created 
    > Note: we've started adding these already in central-services-shared and central-ledger, so make sure to check those codebases for PISP related callbacks
- [x] the list should be divided by PISP/DFSP roles, as not both roles will need all endpoints
- [x] Add to central-services-shared: [here](https://github.com/mojaloop/central-services-shared/blob/master/src/enums/endpoints.js)

**Acceptance Criteria**:
- [x] Designs are up-to date
- [x] Code Style & Coverage meets standards

## **Pull Requests**:
- [x] https://github.com/mojaloop/central-services-shared/pull/243
- [x] https://github.com/mojaloop/pisp/pull/50
- [x] https://github.com/mojaloop/central-services-shared/pull/244

## **Follow-up**:
- [ ] Add these new endpoints as enums on `central-ledger` [see #409](https://app.zenhub.com/workspaces/pisp-5e8457b05580fb04a7fd4878/issues/mojaloop/mojaloop/409)
- [x] Follow up potential design issue with some callbacks @lewisdaly 

**Dependencies**:
- N/A

## **Accountability**:
- Owner: @lewisdaly 
- QA/Review: TBC

**Comment by lewisdaly** [comment]
Oops: https://github.com/mojaloop/central-services-shared/blob/master/src/enums/endpoints.js#L74
