### ISSUE TITLE
[central-ledger] Add PISP Related Endpoints to database seeds

### ISSUE THREAD

**Issue by lewisdaly** [mojaloop/mojaloop#409]
## **Goal**:
As a `DFSP/PISP`
I want `to be able to register callback endpoints with the mojaloop switch`
so I `can support PISP functions`

**Tasks**:
- [x] Add the new endpoint types defined in [this commit](https://github.com/mojaloop/central-services-shared/commit/1450599c595d0dbd86feeeade8694910b4188ecf) to the database seed
- [x] bump and release on the `central-ledger:pisp` repo
- [x] update end to end onboarding (postman) collections to register these new endpoints in `mojaloop/pisp/docker-local` for each DFSP/PISP

Links:
- [PISP endpoint type reference](https://github.com/mojaloop/pisp/blob/master/docs/participant_endpoint_enums.md)
- [`central-ledger` seed file](https://github.com/mojaloop/central-ledger/blob/master/seeds/endpointType.js)

**Acceptance Criteria**:
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] E2E Tests pass

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
