### ISSUE TITLE
[auth-service] - Update auth-service swagger and sequence diagrams

### ISSUE THREAD

**Issue by ramanmangla** [mojaloop/mojaloop#412]
## **Goal**:
As an `OSS Dev`
I want to `update OpenAPI specification files`
so that ` there is 1 source of truth for the API and for others to build on`.

**Examples**:
- POST /consents: body ***credential*** should be ***null***, OpenAPI requires an ***object***
- POST /consents: body ***scope*** should be called ***action*** and should be an ***array*** instead of ***string***
- POST /thirdpartyRequests/transactions/{ID}/authorizations: OpenAPI specifies incorrect URI starting with ***/thirdPartyRequest***

**Tasks**:
- [ ] Investigate inconsistencies between OpenAPI files and sequence diagrams
- [ ] Update OpenAPI/sequence diagrams after team consensus
- [ ] Update handler and domain logic if required
- [ ] Update handler and domain unit/integration tests if required

**Acceptance Criteria**:
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by lewisdaly** [comment]
This may be being covered in: mojaloop/mojaloop#390

**Comment by lewisdaly** [comment]
We might be able to roll this in with #414 changes

**Comment by lewisdaly** [comment]
I think this has been covered elsewhere. Closing for now since we are making larger changes to the api spec.
