### ISSUE TITLE
Auth service: Modify registration and signing verification logic

### ISSUE THREAD

**Issue by kkzeng** [mojaloop/mojaloop#414]
**Goals**

As a developer, I want to ensure that FIDO verification concepts are used to register and authenticate users.

**Tasks**

- [ ] Investigate the use of fido2-lib node package to handle the fido2 verification process
- [ ] If it is feasible, implement verification using the library - need to store some new things like a counter variable
- [ ] If it is not feasible to use fido2-lib, at least modify verification function to accept additional data: clientDataJSON (contains challenge) and authData since the signature generated on the client-side will be a signature over those 2 pieces of data.

**Comment by lewisdaly** [comment]
Hey @kkzeng - a couple clarifying questions:

> generateChallenge (which may be renamed) will provide some object like credentialOptions or attestationOptions which could specify attestation options for the authenticator.

So the auth-service will still specify _something_ to the authenticator, just not the challenge. Is that correct?

> Include other params like algorithm, rpId, rpName, challenge size.
> Other than challenge, specifies those params for authenticator (FIDO client)
> Needs changes to the model to specify those params (specified later on) - perhaps challenge object can be augmented to have those fields?

Can we specify what those params will be now in the API? Or is that something that a Mojaloop Hub or DFSP running their own auth service will want to specify?


> After posting the thirdPartyRequests/transactions, the user should receive some signingOptions

So the PISP app will need to get some other options before signing and sending a `PUT /authorizations/{id}`? Is that something that could be cached? Or will it need to be fetched every time from the auth service before signing a transaction?

**Comment by kkzeng** [comment]
Hey @lewisdaly thanks for the great questions!

(1) The auth-service will specify something to the authenticator - **including** the challenge. For some reason, the registration process still uses the challenge but it doesn't verify any signature. It just compares equality it seems and uses it as some kind of identifier?

(2) Yeah, we can specify the params now - if you reference the [fido2 client plugin](https://github.com/mojaloop/fido2-client-plugin/blob/master/lib/fido2_client.dart). We can see what the client needs in order to begin the registration as well as signing later on. 

However, I'm not quite sure I have the context to be able to say whether or not we want the Mojaloop Hub/DFSP to specify. 

(3) If you refer to the  [fido2 client plugin](https://github.com/mojaloop/fido2-client-plugin/blob/master/lib/fido2_client.dart), the only option needed to be sent seems to be the relying party domain which we can theoretically just hardcode.

Please let me know if this is all clear enough!

**Comment by kkzeng** [comment]
To be more specific for (2).
For registration, the following params:

String challenge,
String userId,
String username,
String rpDomain,
String rpName,
int coseAlgoValue

and for signing, only the rpDomain is needed.
