### ISSUE TITLE
Compile Typescript to Javascript for production deployment

### ISSUE THREAD

**Issue by eoln** [mojaloop/mojaloop#415]
## **Goal**:
As a Hub Operator I want to run Typescript services as Javascript so that execution env doesn't have to play with Typescript dependencies
**Tasks**:
- [ ] find out proper TS->JS translation method (AOT), experiment with output code optimization 
- [ ] handle paths shortcuts defined in `tsconfig.json` and not properly resolved during TS->JS translation
- [ ] drop any Typescript dependencies from `production`
- [ ] build a container with JS only & adjust docker-compose if needed

**Acceptance Criteria**:
- [ ] thirdparty-api-service 
- [ ] thirdparty-scheme-adapter
- [ ] auth-service
- [ ] Unit Tests pass run against Javascript compiled code
- [ ] Integration Tests pass run against Javascript compiled code
- [ ] Code Style & Coverage meets standards
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by lewisdaly** [comment]
Issue moved to [mojaloop/project #1814](https://github.com/mojaloop/project/issues/1814) via [**ZenHub**](https://www.zenhub.com/)
