### ISSUE TITLE
[thirdparty-scheme-adapter] - CI/CD Automatic Release & Docker Image Publication

### ISSUE THREAD

**Issue by eoln** [mojaloop/mojaloop#416]
## **Goal**:
As a Dev I want to automate GitHub releasing and docker image publication processes so the service publication goes ASAP

**Tasks**:
- [ ] enforce conventional-commit style via git pre-commit hook
- [ ] CI/CD image publication
- [ ] CI/CD GitHub release

**Acceptance Criteria**:
- [ ] git pre-commit hooks protect against not well-formatted commit messages
- [ ] when PR merged with master Docker Image is built and published then the GitHub release is created

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by lewisdaly** [comment]
@eoln has this already been done?
