### ISSUE TITLE
[auth-service] Increasing Test Coverage

### ISSUE THREAD

**Issue by akapur99** [mojaloop/mojaloop#417]
## **Goal**:
As a `auth-service` I want to to have improved test coverage/readability to reduce error likelihood
I also want to consolidate common mocked resources to improve test clarity / ease of testing. 
Reference Issue https://github.com/mojaloop/auth-service/issues/40
Following ticket #384

**Tasks**:
- [x] Increase Unit Test Coverage - with emphasis on unlinking flow
- [x] Add tests where generatePatchConsentRequest is called with ACTIVE/ invalid Consent argument
- [x] Add tests where revokeConsentStatus is called with REVOKED/ invalid Consent argument
- [x] Seed with data with REVOKED consent status + add tests for revoke related logic
- [x] Create a central data file for all common mocked resources used in unit tests. Refactor tests to use the data file
- [x] Improve test descriptions for clarity where needed

**Acceptance Criteria**:
- [x] Designs are up-to date
- [x] Unit Tests pass
- [x] Integration Tests pass
- [x] Code Style & Coverage meets standards

## **Pull Requests**:
- [ ] https://github.com/mojaloop/auth-service/issues/40

## **Follow-up**:
- N/A

**Dependencies**:
- #358

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
