### ISSUE TITLE
FIDO2/Webauthn server spike

### ISSUE THREAD

**Issue by kkzeng** [mojaloop/mojaloop#419]
**Goals**

As a developer, I want to familiarize myself with the FIDO2 process E2E. I also want to be able to determine how much work it will be to modify the auth-service.

**Tasks**

- [ ] Build a simple WebAuthn conforming server using fido2-lib - may be possible to follow some examples from other WebAuthn server demos.
- [ ] Connect an example app using the FIDO client plugin for Flutter that we built to the WebAuthn server
- [ ] Complete E2E registration process
- [ ] Complete E2E signing process
