### ISSUE TITLE
[thirdparty-scheme-adapter] - BDD Tests for src/shared

### ISSUE THREAD

**Issue by eoln** [mojaloop/mojaloop#420]
## **Goal**:
`As a` Non-technical Stakeholder

`I want to` have BDD tests for code stored in `src/shared` folder
  
`so that` I can understand which part of shared utility code is tested 

**Acceptance Criteria**:
- [ ] BDD tests are covering at least 80% of the source code

**Complexity**: <Medium> > there is a need to identify reusable parts of tests to make the implementation of the steps much compact

**Uncertainty**: <Low> > there is BDD test runner with examples implemented

---

**Tasks**:
- [ ] RedisConnection
- [ ] KVS
- [ ] PubSub
- [ ] PersistentModel

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by lewisdaly** [comment]
Issue moved to [mojaloop/project #1817](https://github.com/mojaloop/project/issues/1817) via [**ZenHub**](https://www.zenhub.com/)
