### ISSUE TITLE
thirdparty-scheme-adapter: shared state middleware

### ISSUE THREAD

**Issue by eoln** [mojaloop/mojaloop#423]
## Shared state middleware plugin:
As a Developer 
I want to have a shared `state` property on handlers' request 
so that all handlers can reuse the same instances of KVS/PubSub/WSO2Auth/Logger/tlsCreds to create a new ThirdpartyRequest instance

**Tasks**:
- [x] Typescript interface for WSO2Auth in sdk-standard-components
- [x] config for WSO2Auth
- [x] config for tlsCreds
- [x] hapi server plugin for shared `state` which instantiates all necessary objects: KVS/PubSub/WSO2Auth/Logger/tlsCreds

**Acceptance Criteria**:
- [x] Designs are up-to date
- [x] Unit Tests pass
- [x] Integration Tests pass
- [x] Code Style & Coverage meets standards
- [x] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.

## **Pull Requests**:
- [x] https://github.com/mojaloop/sdk-standard-components/pull/96
- [ ] https://github.com/mojaloop/thirdparty-scheme-adapter/pull/23
## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
