### ISSUE TITLE
SDKLogger Typings

### ISSUE THREAD

**Issue by eoln** [mojaloop/mojaloop#425]
## **Migrate logger from sdk-scheme-adapter to sdk-standard-components repo**:
As a Scheme integrator 
I want to have a lightweight logger in sdk-standard-components 
so Requests related classes will have their dependencies resolved in-situ

**Tasks**:
- [ ] typing file for Logger

**Acceptance Criteria**:
- [ ] no TS errors in typing file

## **Pull Requests**:
- [x] https://github.com/mojaloop/sdk-standard-components/pull/97

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by eoln** [comment]
the logger has been already migrated, I will add only TS typings
