### ISSUE TITLE
[central-ledger] Add PISP TP_CB_URL_TRANSACTION_REQUEST_PATCH endpoint to database seeds.

### ISSUE THREAD

**Issue by kleyow** [mojaloop/mojaloop#428]
## **Goal**:
As a `DFSP/PISP`
I want `to be able to register Thirdparty PATCH callback endpoint with the mojaloop switch`
so I `can support PISP functions`

**Tasks**:
- [ ] Add the new TP_CB_URL_TRANSACTION_REQUEST_PATCH endpoint type to the database seed
- [ ] bump and release on the `central-ledger:pisp` repo
- [ ] update end to end onboarding (postman) collections to register the new TP_CB_URL_TRANSACTION_REQUEST_PATCH endpoint in `mojaloop/pisp/docker-local` for each DFSP/PISP
- [ ] Update endpoint type in `central-services-shared`  https://github.com/mojaloop/central-services-shared/blob/master/src/enums/endpoints.js and build
- [ ] Update endpoint type in `thirdparty-api-adapter` https://github.com/mojaloop/thirdparty-api-adapter/blob/master/ambient.d.ts

Links:
- [PISP endpoint type reference](https://github.com/mojaloop/pisp/blob/master/docs/participant_endpoint_enums.md)
- [`central-ledger` seed file](https://github.com/mojaloop/central-ledger/blob/master/seeds/endpointType.js)

**Acceptance Criteria**:
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] E2E Tests pass

## **Pull Requests**:
- []

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by lewisdaly** [comment]
Issue moved to [mojaloop/project #1822](https://github.com/mojaloop/project/issues/1822) via [**ZenHub**](https://www.zenhub.com/)
