### ISSUE TITLE
reusable mocks for unit tests

### ISSUE THREAD

**Issue by eoln** [mojaloop/mojaloop#430]
## **Goal**:
As a Tester 
I want to reusable mocks 
so that I can spend less time creating unit-tests

**Tasks / Scopes**:
- [ ] logging
- [ ] request toolkit
- [ ] KVS/PubSub
- [ ] Models 
- [ ] handlers
TBD [ @? ]

**Repos**
- [ ] auth-service
- [ ] thirdparty-api-adapter
- [ ] thirdparty-scheme-adapter
- [ ] pisp-demo-server

**Acceptance Criteria**:
- [ ] Unit Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by lewisdaly** [comment]
We need to think about how to share these mocks easily between our repos.

Perhaps we can also just look at one repo to begin with as well.

**Comment by lewisdaly** [comment]
Issue moved to [mojaloop/project #1816](https://github.com/mojaloop/project/issues/1816) via [**ZenHub**](https://www.zenhub.com/)
