### ISSUE TITLE
[pisp] - Add thirdparty-scheme-adapter to PISP and DFSP backends in docker-local

### ISSUE THREAD

**Issue by kleyow** [mojaloop/mojaloop#431]
## **Goal**:
As a developer I want to have the scheme adapter set up so that I can add e2e tests.

**Tasks**:
- [ ] thirdparty-scheme-adapter are added to dfsp A/dfsp B/pisp backends in `docker-local`

**Acceptance Criteria**:
- [x] thirdparty-scheme-adapters are added and tests pass.

## **Pull Requests**:
- [x] https://github.com/mojaloop/pisp/pull/68

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
