### ISSUE TITLE
[auth-service] - use Logger from sdk-standard-components

### ISSUE THREAD

**Issue by eoln** [mojaloop/mojaloop#432]
**Summary**:
already service is using Logger from sdk-central-services-logger which is incompatible with Mojaloop/Thridaparty Requests classes

**Severity**:
High

**Priority**:
Critical

**Specifications**
  - Component (if known): all

**TASKS**:
- [x] identify false positive test for `UnhandledPromiseRejection` and create the [ticket](https://app.zenhub.com/workspaces/mojaloop-project-59edee71d1407922110cf083/issues/mojaloop/project/1766)
- [x] update to latest sdk-standard-components where the latest Logger interface is defined
- [x] fix config issues introduced by sdk-standard-components v12 breaking change

**PR**:
- [ ] https://github.com/mojaloop/auth-service/pull/56
