### ISSUE TITLE
Enhance Central-KMS to provide a Health Probe Service for Liveliness Checks

### ISSUE THREAD

**Issue by mdebarros** [mojaloop/mojaloop#87]
**Goal**:
As DevOps I want Health liveness Probe on the microservice so that the health of the service can be monitored.

**Tasks**:
- [ ] Add health liveness service operation
- [ ] Test health liveness service operation
- [ ] Add unit test for health liveness service operation
- [ ] Update K8s deployments to utilise liveness probe
- [ ] Update Helm deployments to utilise liveness probe
- [ ] Add health readyness probe operation
- [ ] Test health readyness service operation
- [ ] Add unit test for readyness liveness service operation
- [ ] Update K8s deployments to utilise readyness probe
- [ ] Update Helm deployments to utilise readyness probe

**Acceptance Criteria**:
- [ ] Add new feature to Micro-service API to expose a JSON HTTP REST service for the health readyness probes that returns HTTP 200
- [ ] Configure Health liveness Probe on Kubernetes Deployment
- [ ] Add new feature to Forensic Logging Sidecar API to expose a JSON HTTP REST service for the health readyness probes that returns HTTP 200, and checks for any dependencies (i.e. DB connectivity)
- [ ] Configure Health readyness Probe on Kubernetes Deployment

**Dependencies**:
N/A

**Comment by elnyry** [comment]
Outdated; current issues are tracked here - https://github.com/mojaloop/project/issues
