### ISSUE TITLE
Enhance Forensic-logging-sidecar to provide a Health Probe Service for Liveliness Checks

### ISSUE THREAD

**Issue by mdebarros** [mojaloop/mojaloop#89]
**Goal**:
As DevOps I want Health liveness Probe on the microservice so that the health of the service can be monitored.

**Tasks**:
- [x] Add health liveness service operation
- [x] Test health liveness service operation
- [x] Add unit test for health liveness service operation
- [x] Update K8s deployments to utilise liveness probe
- [x] Update Helm deployments to utilise liveness probe
- [x] Add health readyness probe operation
- [x] Test health readyness service operation
- [x] Add unit test for readyness liveness service operation
- [x] Update K8s deployments to utilise readyness probe
- [x] Update Helm deployments to utilise readyness probe

**Acceptance Criteria**:
- [x] Add new feature to Micro-service API to expose a JSON HTTP REST service for the health readyness probes that returns HTTP 200
- [x] Configure Health liveness Probe on Kubernetes Deployment
- [x] Add new feature to Forensic Logging Sidecar API to expose a JSON HTTP REST service for the health readyness probes that returns HTTP 200, and checks for any dependencies (i.e. DB connectivity)
- [x] Configure Health readyness Probe on Kubernetes Deployment

**Dependencies**:
N/A

**Comment by elnyry** [comment]
Outdated; current issues are tracked here - https://github.com/mojaloop/project/issues (this seems to be done anyway)
