### ISSUE TITLE
Central-Ledger unit tests require that the following ENV Var CLEDG_HOSTNAME=http://central-ledger is set to pass successfully

### ISSUE THREAD

**Issue by mdebarros** [mojaloop/mojaloop#96]
**Goal**:
As a deployer of the system I would like an ILP Ledger Adapter that can integrate with my existing ledger database without requiring me to implement any ILP functionality.
As a Developer I want to be able to test Unit Tests succesfully based on the ENV/Configuration files for the HOSTNAME dynamically as opposed to using "http://central-ledger" as hard-coded in the current unit test code.

**Tasks**:
- [ ] Modify unit test code to use dynamic env configuration for HOSTNAME parameter
- [ ] Test unit test code

**Acceptance Criteria**:
- [ ] Unit tests pass successfully based on the value of default.json 
- [ ] Unit tests pass successfully based on the value of CLEDG_HOSTNAME env parameter.

**Dependencies**:
n/a

**Comment by elnyry** [comment]
Outdated; current issues tracked here - https://github.com/mojaloop/project/issues
